### ISSUE TITLE
Update Retry Middleware once New Error API is live

### ISSUE THREAD

**Issue by willhug** [yarpc/yarpc-go#1080]
#1076 introduces a retry middleware that makes assertions based on the errors returned from handlers.  But, concurrently @peter-edge is working on #1064 which will introduce much more granular error apis.  Once the error pr is out we should update the retry error reading/generation.

**Comment by peter-edge** [comment]
@willhug Not sure if we still need to do anything here, check out the relevant code, I think you might want to update what is retryable and what is not.
