### ISSUE TITLE
Validate outgoing requests

### ISSUE THREAD

**Issue by abhinav** [yarpc/yarpc-go#109]
All outgoing requests should be validated by the system.

**Comment by breerly** [comment]
In python I'm considering adding the validator to the `Channel` so peeps can't opt-out.

**Comment by abhinav** [comment]
Worth noting that in Python, Channel has a `call` method similar to `Outbound`.

**Comment by breerly** [comment]
@abhinav do you remember what we meant specifically here? Is this worth closing?
