### ISSUE TITLE
Many new dependencies brought in by YARPC

### ISSUE THREAD

**Issue by klnusbaum** [yarpc/yarpc-go#1095]
I'm working on the Dosa project and currently, in our `glide.yaml` file, we have yarpc pinned to `^1.7.1`.

Today, I ran `glide up` and noticed that we're now pulling in a [bunch of new dependencies](https://gist.github.com/klnusbaum/d3149824a31251f6c1215773279a287e) including:

- perks
- facebook/clock
- a bunch of protobuf repos
- a bunch of prometheus repos
- tally
- multierr
- zap

Making some educated guesses, I tried changing the pin of our yarpc version from `^1.7.1` to `~1.7.1` (and also adding a pin for `go.uber.org/yarpc` to `~1.7.1`) to see if it was yarpc that was brining in all of these changes. Sure enough, after clearing the glide cache and re-running `glide up`, [none of these new dependencies are brought in](https://gist.github.com/klnusbaum/5176ab055c5eb3350c11fee59005096b).

While bringing in some of these dependencies might be ok, all of them together is just too much for DOSA, especially zap. I'm not sure what the best course of action is, but is there some way to cut down on all of the external dependencies users of yarpc have to bring in? Or at least make them opt in? If not, I think DOSA is going to be stuck yarpc version `~1.7.1` for the foreseeable future.

More context: https://github.com/uber-go/dosa/pull/167

**Comment by rkuris** [comment]
+1 on fixing this

**Comment by blampe** [comment]
Followed up in person, turns out DOSA had some low-hanging fruit in their `glide.yaml` (specifying sub-packages; eliminating duplicated dependency on yarpc provided by go.uber.org and github.com) that should help alleviate pain points here.
