### ISSUE TITLE
Cannot reliably test unexpected errors

### ISSUE THREAD

**Issue by Willyham** [yarpc/yarpc-go#1107]
I'm writing failure tests against a YARPC service. For my known error cases, I'm comparing the error received from an endpoint with the error defined in my Thrift file, which is fine. However, for the unexpected case, I cannot find a simple way to assert that the error I've received is correct because `errors.remoteUnexpectedError` is internal. I don't want to rely on string matching for this.

**Comment by peter-edge** [comment]
All of that is going away, see `api/yarpcerrors` and #1098 .

**Comment by peter-edge** [comment]
@Willyham this should be addressed by the new `yarpcerrors` package - check it out and let me know if there's something else you need.

**Comment by peter-edge** [comment]
Re-open this if this is not addressed by that package.
