### ISSUE TITLE
Translate panics in Handlers to UnexpectedErrors

### ISSUE THREAD

**Issue by abhinav** [yarpc/yarpc-go#111]
Right now, we're letting panics bubble up to the HTTP/TChannel server. We should catch them and translate them to unexpected errors.

We'll want to log the stack trace in case of panics.

**Comment by breerly** [comment]
@kriskowal this one is pretty scary :)

**Comment by blampe** [comment]
We'd still kill the process after trying to return an unexpected, right?

**Comment by abhinav** [comment]
No, we'll treat the panic as isolated to that request. The HTTP (and presumably TChannel) library already does this, BTW.  The issue is that they'll return a 500/Error frame with a message they chose. We want an a standard unexpected error message sent to the user.

**Comment by prashantv** [comment]
TChannel doesn't do this yet, we've been meaning to expose an option to enable this, but it's not done.

Since it would be a functional change, it has to be opt in for TChannel.Would

 be good if YARPC did this from the beginning, and maybe allows opt out (can be deferred)

**Comment by abhinav** [comment]
Done in #315

**Comment by breerly** [comment]
This is done!
