### ISSUE TITLE
TChannel flaky test

### ISSUE THREAD

**Issue by peter-edge** [yarpc/yarpc-go#1116]
https://travis-ci.org/yarpc/yarpc-go/jobs/243653097#L1140

**Comment by peter-edge** [comment]
This is still happening

**Comment by peter-edge** [comment]
![image](https://user-images.githubusercontent.com/4228796/27285501-3ab6c82e-54fd-11e7-985d-f4b6066635e5.png)

**Comment by kriskowal** [comment]
Should be addressed by #1130
