### ISSUE TITLE
Hide {Local,Remote}{BadRequest,Unexpected}Error in an internal package

### ISSUE THREAD

**Issue by abhinav** [yarpc/yarpc-go#112]
Right now, users could use these from the `transport` package if they wanted. Do we want to disallow that?

Worth noting that moving to an internal package isn't as straightforward because the corresponding types for these functions implement package-local functions of the `BadRequest` and `UnexpectedError` interfaces.

**Comment by breerly** [comment]
@abhinav perhaps lets start with these in internal to reduce the API surface - we can always export them later.

**Comment by prashantv** [comment]
@abhinav i think you can work around the implementing the private methods by exporting dummy implementations from the same internal package that have the private method. Then if you embed those dummy types, you should satisfy the interface.

**Comment by abhinav** [comment]
Oh, that makes sense. Cool.
