### ISSUE TITLE
TestRoundTrip/enveloped(true)/multiplexed(false) flaky

### ISSUE THREAD

**Issue by peter-edge** [yarpc/yarpc-go#1126]
![image](https://user-images.githubusercontent.com/4228796/27286358-27d80d14-5500-11e7-8ee6-d4ca9ece0648.png)

**Comment by blampe** [comment]
Please prioritize this, it's been flaking since April :( https://github.com/yarpc/yarpc-go/issues/947

**Comment by kriskowal** [comment]
Should be addressed by #1130

**Comment by kriskowal** [comment]
Please reopen if we see this again.
