### ISSUE TITLE
Add YARPCError interface to convert self to a YARPC error

### ISSUE THREAD

**Issue by abhinav** [yarpc/yarpc-go#1157]
Discussed this offline, reporting here so it doesn't get lost.

We should allow rich user-defined `error`s returned by user handlers to
implement the interface,

```go
// Naming TBD
type YARPCError interface {
  ToYARPCError() error
}
```

If an error returned by a user handler implements this interface, this
function will be called to convert that error into a YARPC error (from the
yarpcerrors package).

This will allow rich user errors to not lose any information while the user is
dealing with them and conveniently convert to YARPC native errors.

```go
type ErrUserNotFound struct{ User string }

func (e ErrUserNotFound) Error() { ... }

func (e ErrUserNotFound) ToYARPCError() error {
  return yarpcerrors.NotFoundf("user %q not found", e.User)
}
```

**Comment by peter-edge** [comment]
I'm not completely convinced we want to do this after thinking about it a bit more, let's catch up offline this week.

**Comment by peter-edge** [comment]
Talked offline, closing this for now
