### ISSUE TITLE
errors: Untrusted strings passed to Sprintf

### ISSUE THREAD

**Issue by abhinav** [yarpc/yarpc-go#1158]
We currently pass `err.Error()` to `Sprintf` indiscriminately when building
YARPC errors from user errors. This is undesirable because if the string
contains `%v`, we'll get an ugly string like `%(MISSING)` instead.

Example: https://github.com/yarpc/yarpc-go/blob/95c2b58613657cd7bd034b1975813701a6e87ca9/api/yarpcerrors/errors.go#L49

We should check if the list of formatting arguments is non-empty before
calling Sprintf.

**Comment by kriskowal** [comment]
Can you clip an example of the unsafe code? We should never pass `err.Error()` as the format specifier to Sprintf, but it would be safe to append ": cause %s" to the format specifier and err.Error() to the args slice.

**Comment by abhinav** [comment]
Added example

**Comment by peter-edge** [comment]
Doing this in #1098
