### ISSUE TITLE
Improvements to x/config

### ISSUE THREAD

**Issue by mhamrah** [yarpc/yarpc-go#1169]
I have a use case where I'd like to call the [http.Mux()](https://godoc.org/go.uber.org/yarpc/transport/http#Mux) method on an inbound. In order to do so I have to build the inbound manually. This is for the trivial example, but becomes extremely annoying when combined with an additional inbounds/outbounds.

x/config allows you to define inbounds/outbounds from a yaml file, but all you get back from the Load* options is a yarpc.Config, which doesn't allow for post-manipulation of inbounds. Also x/config requires you to explicitly register transports to the configuration via RegisterTransport(), which is rather annoying. Can't the default transports that come packaged with yarpc be bundled automatically?

It would be nice if it were easier to add/change outbounds/inbounds while you were building up the yarpc/config returned from x/config, with some definitions coming from yaml and some defined explicitly. It would also be nice if you could define a struct that works with x/config so you can pass in part of a yaml file already loaded without having to fall back to map[string]interface.

A robust setup example, with some environment config for running locally vs prod (i.e. setting exposed/outbound host:port) would be:

- Exposing at least two inbounds of: http, tchannel, and grpc imports with corresponding json, thrift and protobuf encodings.
- Exposing at least two outbounds, of which the generated handler service uses to handle an inbound method.
- Metrics, either Prom, Tally or Pally
- Tracing
- Some specific inbound or outbound transport configurations, like setting round-robin etc.
- Http.Mux, so users can add their own http handlers (for additional diagnostic pages, or to serve http)

**Comment by peter-edge** [comment]
@breerly what's the status on this?
