### ISSUE TITLE
2.0 Wishlist Tracking Issue

### ISSUE THREAD

**Issue by peter-edge** [yarpc/yarpc-go#1197]
## LifecycleOnce semantics require a lock to implement SetRouter without setting off a data race with go test -race

Right now, we use the `LifecycleOnce` interface to do locking in `transport.Inbound` and `transport.Outbound` implementations. However, `transport.Inbound` has the `SetRouter` function, which requires setting a `transport.Router`. To do this without setting off a data race condition with `go test -race`, you have to separately lock access in `SetRouter`, and internal `start` and `stop` implementations - go cannot detect that the implementation of `LifecycleOnce` happens to lock where appropriate. I ran into this problem a lot when working on FX in the past, and technically, not locking the `SetRouter` setter is an issue.

## thriftrw-plugin-yarpc should probably be named thriftrw-plugin-yarpc-go

The call right now to use the yarpc go plugin is `thriftrw --plugin=yarpc`. This should probably be `thriftrw --plugin=yarpc-go` - the output of `thriftrw-plugin-yarpc` is golang specific stubs, so when we talk about java etc, there should be a differentiation (there's technically nothing preventing thriftrw-go from generating java stubs).

## Clarify naming of oneway/unary

Users have brought up that they are confused by these terms and they don't connect which RPC messaging patterns they are used to.

## Rework yarpc.Outbounds

Currently, users create a set of outbounds where the key is the service name, and the value is the outbound. This is a bit confusing since `transport.Outbounds` is not actually a collection of outbounds, it contains a single possible outbound for each RPC Type (unary, oneway, etc):

```
type Outbounds map[string]transport.Outbounds
```

Instead, we should make it more obvious that the key is just the outbound key, and that the value is not a set of outbounds, but an `OutboundSpec`:

```
type Outbounds 
```

## Get rid of transport.Procedure{ Service }

```go
type Procedure struct {
	// Name of the procedure.
	Name string

	// Service or empty to use the default service name.
	Service string // <<<<<<<----- we should get rid of this

	// HandlerSpec specifiying which handler and rpc type.
	HandlerSpec HandlerSpec

	// Encoding of the handler, for introspection.
	Encoding Encoding

	// Signature of the handler, for introspection. This should be a snippet of
	// Go code representing the function definition.
	Signature string
}
```

The `Service` string in the Procedure struct can only make sense in a peer to peer request. This is because on the wire, a procedure is a tuple (DispatcherService, ProcedureName) and not, for example (DispatcherService, ProcedureService, ProcedureName).

In a peer to peer connection, you effectively get 3 information: (endpoint, Service, ProcedureName). The endpoint will act as the DispatcherService routing, and the Service will match the Service in the Procedure struct above.

But as soon as you proxify (during distributed routing for example), the endpoint is fixed to the proxy service. This leaves (Service, ProcedureName). Of course the proxy uses the Service to determine which process should receive the request and this leaves Procedure the only variable at the destination.

If ones want to namespace, it is easy to prefix the ProcedureName with a common string:
 - MyService/Get
 - MyService/Set
 - MyService/AutoDestruct

This makes the Service string in the transport.Procedure struct not only useless in most cases, but also really confusing.

#### Path forward

When the Service in transport.Procedure is left to "", yarpc will set the Service to the Dispatcher Service.
We also note that all convenience functions for building transport.Procedure(s) never set the Service in transport.Procedure. This means we can probably deprecate this attribute, and remove the burden of trying to handle multiple "ProcedureService" in the Routing table.

## Remove yarpc.InjectClients

YARPC should use plain-ol' dependency injection, and not provide any DI container-like functionality. This makes YARPC easy to use with a DI/application framework like Fx.

**Comment by breerly** [comment]
My hope is that when customers are migrated to yarpcfx, that we will be able to cut 2.0 without breaking any of them. 

This is because Fx reduces the API surface for initializing YARPC. Alot of these changes relate to that.

**Comment by breerly** [comment]
I want to remove `yarpc.InjectClients` in favor of just leaning on Fx.

**Comment by peter-edge** [comment]
Tracking this internally.
