### ISSUE TITLE
Use proper semantic versioning

### ISSUE THREAD

**Issue by recht** [yarpc/yarpc-go#1206]
v 1.10.0 renamed a package (`encoding/x/protobuf`), which means that some components cannot build any longer. `1.10.0` looks like a semantic version, so is there any chance you could keep to non-breaking changes on minor version bumps?

**Comment by kriskowal** [comment]
I see that we left no document in https://github.com/yarpc/yarpc-go/tree/dev/x to clarify that the "x" stands for "experimental", a place we reserved for incubating new features. That we must fix.

**Comment by peter-edge** [comment]
It's stated in the README.md file at the base of the repository, and was stated in https://github.com/yarpc/yarpc-go/blob/v1.9.0/encoding/x/doc.go. x/ packages are not stable, however as of 1.10.0, the protobuf package is stable.

**Comment by peter-edge** [comment]
https://github.com/yarpc/yarpc-go/pull/1208 adds this to the main x/ package as well.

**Comment by recht** [comment]
It might be that there are comments, but semantic versioning kinda breaks down when one of your dependencies use one of these hidden features from yarpc.

**Comment by breerly** [comment]
Semantic versioning calls for the library to specifically define their public API.

We should be explicitly calling this out in the README under the Stability section. Something like "all exported APIs with the explicit exception of expiremental APIs incubating in an x/ package."

This approach allows us to iterate with early customers to get the shape of new features right before we commit to them.

@recht if you have a specific issue, we're happy to help you move to the new stable APIs - reach out internally.

**Comment by breerly** [comment]
Opening until we add to Stability section of README in addition to the top-level godoc.
