### ISSUE TITLE
Unexplode Request/Response for Raw

### ISSUE THREAD

**Issue by abhinav** [yarpc/yarpc-go#132]
For raw, the request and response body is always `[]byte` so we don't need to explode them into `{Req,Res}{Meta,Body}` like the other encodings.

**Comment by breerly** [comment]
Perhaps - although it might make sense to keep them exploded for consistency.

One could imagine both `json` and `raw` taking advantage of a top-level `ReqMeta` object, with their second params being the `ReqBody` just like a thrift or protobufs encoding.

**Comment by abhinav** [comment]
Sounds good.
