### ISSUE TITLE
Make it easier to construct Call-containing contexts

### ISSUE THREAD

**Issue by akshayjshah** [yarpc/yarpc-go#1350]
Currently, handlers often use `yarpc.CallFromContext` to access metadata about the current request. However, these handlers are difficult to unit test, because constructing a context that contains a call is quite convoluted:

```
import (
    "context"

    "go.uber.org/yarpc"
    "go.uber.org/yarpc/api/encoding"
    pkgencoding "go.uber.org/yarpc/pkg/encoding"
)

func createTestContextWithHeader() (context.Context, error) {
    outboundCall := encoding.NewOutboundCall(
        pkgencoding.FromOptions([]yarpc.CallOption{
            yarpc.WithHeader("foo", "bar"),
        })...,
    )
    request := &transport.Request{}
    return outboundCall.WriteToRequest(context.Background(), request)
}
```

We should provide better test helpers for this.

**Comment by peter-edge** [comment]
@akshayjshah note that there's a bit of a misnomer here: https://github.com/yarpc/yarpc-go/blob/dev/api/encoding/outbound_call.go#L73

We don't actually write anything to the context on the outbound, and there's no equivalent to `inboundCallKey` or `getInboundCall` https://github.com/yarpc/yarpc-go/blob/dev/api/encoding/inbound_call.go#L39. The function `WriteToRequest` is actually confusing.

The fact that you were confused by this though, is a big red flag, as if one of the primary maintainers of yarpc-go didn't see this (I didn't see it either, I started implementing a `ContextFromCallOptions` function), then consumers will be probably more confused.

Maybe this issue should be "deprecate WriteToRequest to not return a context"? @abhinav

**Comment by akshayjshah** [comment]
I think the issue is unchanged - there's no straightforward way to test code that uses `yarpc.CallFromContext`. The code snippet above may be incorrect, as you point out, and that may suggest further API improvements, but the core issue here is that we're missing something like `yarpctest.ContextFromCall`.

**Comment by peter-edge** [comment]
The point here is that we don't store call info on contexts, so the above point remains. There is no concept of `ContextFromCall`, as the context has nothing on it. Does that make sense?

**Comment by peter-edge** [comment]
@akshayjshah if this is a context for an *inbound* call, is this what you're looking for?

```go
func ContextFromRequest(ctx context.Context, request *transport.Request) (context.Context, error) {
    ctx, call := encoding.NewInboundCall(ctx)
    if err := call.ReadFromRequest(request); err != nil {
      return nil, err
    }
    return ctx, nil
}
```

**Comment by peter-edge** [comment]
Is there any duplication here with https://github.com/yarpc/yarpc-go/issues/683? @abhinav

**Comment by abhinav** [comment]
So just to clarify: We need to figure out a cleaner testing strategy for both,
inbound and outbound metadata for both, incoming and outgoing requests.
Specifically,

- I have a handler that has behavior tied to incoming metadata like headers,
  shard key, etc. How do I construct a `Context` with fake metadata on it
  that would be correctly returned by `yarpc.CallFromContext`?
- How do I test that my handler returned the correct response headers?
- How do I ensure (whether with a mock or through some other means) that my
  gateway that makes certain client calls is passing the correct metadata in?
- How do I send fake response headers back to the mock client?

https://github.com/yarpc/yarpc-go/issues/1350#issuecomment-347659209 is close
to how I think we would handle the first case. We need to consider all four
use cases to come up with and commit to an API here.

**Comment by peter-edge** [comment]
@abhinav can I leave this issue to you as well?

**Comment by abhinav** [comment]
Moved to internal ticket T1396783
