### ISSUE TITLE
Support outbound-only TChannel

### ISSUE THREAD

**Issue by yiminc-zz** [yarpc/yarpc-go#1401]
Even if the dispatcher is configured with only one outbound and no inbound.

Here is the code to repro:
	transport, err := ytchannel.NewChannelTransport(ytchannel.ServiceName(serviceName))
	if err != nil {
		panic(fmt.Sprintf("error creating new transport. Err: %v", err))
	}
	outbound := transport.NewSingleOutbound(serviceAddress)
	dispatcher := yarpc.NewDispatcher(yarpc.Config{
		Name: serviceName,
		Outbounds: yarpc.Outbounds{
			serviceName: {
				ServiceName: serviceName,
				Unary:       outbound,
			},
		},
	})
	if err := dispatcher.Start(); err != nil {
		panic(fmt.Sprintf("failed to start yarpc dispatcher. Err: %v", err))
	}

As soon as dispatcher.Start() is called, a OS warning dialog will popup about the application is listening on a port.

**Comment by akshayjshah** [comment]
TChannel is a bidirectional protocol. You can't be just a client; you *must* also listen on a port.

**Comment by prashantv** [comment]
Since we no longer use Hyperbahn, it's not strictly required for clients to listen on a port. We support ephemeral peers fine in our routing layer now, and it's a little annoying for CLI tools that use TChannel to trigger a warning dialog in the OS because they listen.

I think we can change the transport to only listen on a port when the user requires a TChannel inbound?

**Comment by ryanwalls** [comment]
@prashantv Would love to see this capability.  We are running a yarpc client on a desktop app, and opening the inbound port is causing a firewall warning.  Side note, is there a way to configure the TChannel to listen on 127.0.0.1?  We have found if we open server ports and specify listening on 127.0.0.1 that it does not trigger a firewall warning.

**Comment by peter-edge** [comment]
Any idea what the next steps are here? @kriskowal

**Comment by vancexu** [comment]
I tested @ryanwalls and @prashantv idea, and it works. 
sample code:
```
        ch, err := tchannel.NewChannelTransport(
		tchannel.ServiceName(serviceName), tchannel.ListenAddr("127.0.0.1:0"))
	if err != nil {
		logger.Fatal("Failed to create transport channel", zap.Error(err))
	}

	dispatcher = yarpc.NewDispatcher(yarpc.Config{
		Name: clientName,
		Outbounds: yarpc.Outbounds{
			serviceName: {Unary: ch.NewSingleOutbound(hostPort)},
		},
	})
```
