### ISSUE TITLE
crossdock - Rename behaviorSink to crossdock.T

### ISSUE THREAD

**Issue by breerly** [yarpc/yarpc-go#148]
I've struggled with the `sink` terminology in various Crossdock behaviors - for examlpe, https://github.com/yarpc/yarpc-go/pull/147/files#diff-b84f2b2ac8e475a9c0fb53615befc070R47

@kriskowal mentioned the other day that we should piggyback off of Go's `testing.T` naming - that's probably a wise idea.

```go
func Run(t crossdock.T) {
    behavior := t.Behavior
    transport := t.Param("transport")
    encoding := t.Param("encoding")

    t.NoError(err, "something went wrong")
    t.AssertEqual("bob", "tod")
    
    if !t.ChecksTrue(...) {
         ...
    }
}
```

cc @yarpc/golang

**Comment by abhinav** [comment]
This is done
