### ISSUE TITLE
protoc-gen-yarpc-go does not support implement full paths in go_package

### ISSUE THREAD

**Issue by robbertvanginkel** [yarpc/yarpc-go#1547]
`protoc-gen-go` supports having import paths in the `go_package`, which influences what directory the generated code is outputted to. See https://github.com/golang/protobuf/issues/139 for more details.

The `protoc-gen-yarpc-go` plugin currently does not support this, which results in having generated code that should be in the same package/path end up in different paths when calling the `protoc` with the same command but a different plugin. This can be worked around by not using the same output path, but we should probably implement the proposal to have the plugin behave similarly to the default go plugin.

**Comment by peter-edge** [comment]
You can modify go packages to change such items using gogoreplace in gogo/protobuf or just sed, a lot of projects do this including etcd. Long-form packages will cause a lot of issues down the road if you support them at the company
