### ISSUE TITLE
protoc-gen-yarpc-go always generates fx code

### ISSUE THREAD

**Issue by robbertvanginkel** [yarpc/yarpc-go#1548]
After https://github.com/yarpc/yarpc-go/pull/1449, `protoc-gen-yarpc-go` always generates code for `go.uber.org/fx`. 

We should make the fx code generation optional to not force a dependency on fx when using yarpc. Either through an opt out like`--no-fx` or opt in like `plugins=fx`. Leaning towards the second as its similar as how the default go plugin allows you to also generate grpc code.

**Comment by akshayjshah** [comment]
We may need to use an opt-out to preserve backward compatibility.

**Comment by peter-edge** [comment]
In #1449 we talked about adding a `--no-fx` later, I think this is what you'd want.

**Comment by biosvs** [comment]
Generative code is complicated enough, I don't think we'll add `--no-fx` option in a near future.
