### ISSUE TITLE
yarpc outbound leaking implementation detail using http.Client

### ISSUE THREAD

**Issue by AllenLuUber** [yarpc/yarpc-go#1565]
Currently, if you send a HTTP server request with Request.RequestURI field set using Outbound RoundTripper, it will fail with error:
```
code:unknown message:unknown error from http client: Get http://127.0.0.1:55797/foo/bar: http: Request.RequestURI can't be set
```
Either yarpc implementation should reset `Request.RequestURI` on behalf of the user or it should change its implementation to use a RoundTripper. We prefer to go with the latter solution.

**Comment by kriskowal** [comment]
Constructing an HTTP transport and bypassing the Client sounds good to me if we can make it work.
