### ISSUE TITLE
crossdock: Log to crossdock.T

### ISSUE THREAD

**Issue by abhinav** [yarpc/yarpc-go#165]
We should add the ability to log to `crossdock.T` similar to `testing.T`. For the normal case, that would just log to stdout, but for the crossdock test, we can wrap the `testing.T` into a `crossdock.T`, and log to the test object. This will make the tests silent except in case of failure or when we use `-v`.

**Comment by breerly** [comment]
Moved to https://github.com/crossdock/crossdock-go/issues/4
