### ISSUE TITLE
x/net source constraint is annoying

### ISSUE THREAD

**Issue by UberFarmer** [yarpc/yarpc-go#1697]
https://github.com/yarpc/yarpc-go/blob/17c9ad0932d439bd0651d70dd5283da7bb4c8ab2/glide.yaml#L42

My project uses dep and depends on yarpc-go. When running `dep ensure`, I get the following output:
```
[INFO]  failed to handle solve conflicts: No versions of go.uber.org/yarpc met constraints:
	v1.35.2: Could not introduce go.uber.org/yarpc@v1.35.2, as it depends on golang.org/x/net from https://github.com/golang/net, but golang.org/x/net is already marked as coming from golang.org/x/net by [8 other dependencies]
```

This can be worked around using this override in my Gopkg.toml:
```
[[override]]
  name = "golang.org/x/net"
  source = "golang.org/x/net"
```

Looks like the source is hardcoded to `github.com/golang/net` in glide.yaml. Any chance this source constraint in glide.yaml can be removed?

**Comment by abhinav** [comment]
The constraint looks like it was added because we were having periodic issues
resolving golang.org repos. It should be safe to drop now. Would you mind
making a PR?
