### ISSUE TITLE
TChannel: ResponseWriter with empty body won't write headers

### ISSUE THREAD

**Issue by abhinav** [yarpc/yarpc-go#179]
The TChannel inbound won't write the application headers to arg2 until `Write()` is called. So if you have an empty body and don't call `Write()` the headers won't get written either.

https://github.com/yarpc/yarpc-go/blob/master/transport/tchannel/handler.go#L185

**Comment by prashantv** [comment]
Close should probably write headers if they're not written yet.

**Comment by kriskowal** [comment]
@abhinav This is stale. Can we close it?

**Comment by abhinav** [comment]
Turns out this was still an issue. Fixing.
