### ISSUE TITLE
Application middleware

### ISSUE THREAD

**Issue by abhinav** [yarpc/yarpc-go#180]
Creating this issue to discuss how we want application middleware to look.

Something that came up during the in-person discussion: Thrift middleware could have a generic request body shape with an interface similar to the following:

``` go
type ReqBody interface {
    GetParam(name string) (interface{}, ok bool)
    SetParam(name string, value interface{}) error
    Params() []string
}
```

CC @yarpc/yarpc @shawnburke

**Comment by kriskowal** [comment]
Middleware as defined today carry an opaque body. We can revisit this issue when it comes up again, but we do not have a motivating use case currently.
