### ISSUE TITLE
Baggage: Retrieve all entries

### ISSUE THREAD

**Issue by abhinav** [yarpc/yarpc-go#188]
We should figure out if we need a function that allows users access to all baggage added to the context.

Couple things to keep in mind:
- opentracing doesn't currently offer a way to do this, so this may require work there after we integrate with it.
- We shouldn't expose a plain `map[string]string` because the keys are case insensitive (canonicalized to lower case), which is a detail the user is not aware of. We would need either a custom type with accessor functions (`Get(key)`), or a `CanonicalizeBaggageKey(key)` function.

**Comment by kriskowal** [comment]
Since the time we created this issue, we have moved to using opentracing as the API for baggage.
