### ISSUE TITLE
Switch case fall through requires `fallthrough` keyword

### ISSUE THREAD

**Issue by justinjc** [yarpc/yarpc-go#1898]
The comment here suggests that we want this case to fall through, but this needs an explicit `fallthrough` keyword to work.

https://github.com/yarpc/yarpc-go/blob/83d7c24798f05a6e056f4b50e1af968dc938d934/yarpcconfig/chooser.go#L297

**Comment by AlexAPB** [comment]
Hey @justinjc, in this case I believe that the behavior is correct and that `fall through` is a poor choice of words given the context. The only acceptable number of peer list updaters for a single outbound config is one. 
- Zero, means no updater is configured and therefore no peers
- More than one means that you're getting peers from multiple sources (which could be valid) but is not supported in YARPC today.

Note that the the zero and +1 cases return early with an error, so the correct case logic continues after the switch. Feel free to re-open if you find some reproducible buggy logic!

**Comment by justinjc** [comment]
Ah I see, makes sense. Thanks!
