### ISSUE TITLE
Design - allow only 1 outbound per-rpc object

### ISSUE THREAD

**Issue by breerly** [yarpc/yarpc-go#191]
Instead of taking a `map[string]Outbound`, lets have the rpc object take only 1 outbound (which can be used to make custom outbound behavior).

This way we can create ship a `ServiceMapOutbound(map[string]Outbound)` which has the same behavior.

**Comment by abhinav** [comment]
Having a single outbound which encapsulates a `map[string]Outbound` means that you can't resolve the Outbound until someone tries to send a request through it. This means that a typo in the service name will manifest itself as an error while the service is serving requests, not at start-up. I would much rather have an interface with a `GetOutbound(serviceName string)` method (or similar). This will allow outbounds to be resolved at start-up time when `rpc.Channel` is called. If there are typos in the service name, the service will simply fail to start up.

**Comment by abhinav** [comment]
Although, if people are calling `rpc.Channel` from their handlers instead of injecting clients into their handlers at start-up, this is still a problem.

**Comment by breerly** [comment]
Closing this for now - It's probably ok to have outbounds be composable *only* on a per-service basis.
