### ISSUE TITLE
Unable to send []byte{} as header for raw tchannel client request

### ISSUE THREAD

**Issue by breerly** [yarpc/yarpc-go#199]
I would expect to, from a pure-tch client, be able to make a raw request with no headers supplied, `[]byte{}`, like so:

```
arg2, arg3, _, err := raw.Call(
    ctx,
    ch,
    ch.PeerInfo().HostPort,
    ch.ServiceName(),
    "echo",
    []byte{}, // headers here
    []byte("hello"),
)
```

Instead, I get the following error:

```
tchannel.SystemError{code:0x6, msg:"BadRequest: failed to decode \"raw\" request headers for procedure \"echo\" of service \"holler\" from caller \"holler\": EOF", wrapped:error(nil)}
```

**Comment by kriskowal** [comment]
Since we found this issue, we decided that YARPC raw uses the Thrift convention for encoding headers in arg2. Any service that needs genuinely raw TChannel will have to break glass. RPC has to impose an encoding convention for headers.
