### ISSUE TITLE
RFC: Opaque Headers type

### ISSUE THREAD

**Issue by abhinav** [yarpc/yarpc-go#212]
As part of https://github.com/yarpc/yarpc-go/issues/68, we'll be moving `transport.Headers` to `yarpc.Headers`. While at it, I think we should also convert headers into an opaque type. Right now,

```go
type Headers map[string]string

func (Headers) Set(k, v string) { .. }
func (Headers) Ge(k string) (v string, ok bool) { .. }
func (Headers) Del(k string) { .. }
```

We always normalize the key to lower case. An issue with keeping this as a public type alias is that it's possible for someone to do,

```go
h := Headers{"Upper-Case": "foo"}
h.Get("Upper-Case")  // this will fail
```

A workaround to that is doing what `net/http` does: Exposing a [`CanonicalizeHeaderKey`](https://golang.org/pkg/net/http/#CanonicalHeaderKey) function.

Instead, though, I propose that we make `Headers` an opaque struct or an interface.

```go
type Headers struct {
  items map[string]string
}

func NewHeaders() *Headers { .. }
func (*Headers) Set(k, v string) { .. }
func (*Headers) Ge(k string) (v string, ok bool) { .. }
func (*Headers) Del(k string) { .. }
```

A disadvantage of the opaque type is that map literals are no longer supported. You cannot do, `Headers{"foo": "bar"}`. We can work around that by supporting chaining of `Set` calls.

```go
ReqMeta{
  Headers: NewHeaders().Set("foo", "bar"),
}
```

We can also add a `SetMany` (or similar) function:

```go
NewHeaders().SetMany(map[string]string{"foo": "bar"})
```

This will ensure that users cannot create invalid `Headers` objects.

Thoughts? @yarpc/golang

**Comment by breerly** [comment]
+1 - this is a nice improvement

I suggest starting with just `Set,Get,Del`, we shouldn't add `SetMany` unless customers fight for it's existence.

**Comment by kriskowal** [comment]
:ok:. Alternatively to SetMany, we could have a copy constructor.

**Comment by abhinav** [comment]
I'll start off without `SetMany`. We can add the copy constructor, `SetMany`, or `Merge` as necessary.

**Comment by prashantv** [comment]
+1 for opaque headers. I do like the ability of SetMany. Chained `Set` + copy constructor are probably enough for now

**Comment by abhinav** [comment]
Done
