### ISSUE TITLE
Headers: Tests for empty header values

### ISSUE THREAD

**Issue by abhinav** [yarpc/yarpc-go#214]
We should verify that stuff works in that case

**Comment by breerly** [comment]
+1 - should add this to the headers crossdock test :)

**Comment by kriskowal** [comment]
Running out of time for this. Need a volunteer.

**Comment by kriskowal** [comment]
Handing over to @bombela

**Comment by abhinav** [comment]
We already have tests for this.

https://github.com/yarpc/yarpc-go/blob/dev/internal/crossdock/client/headers/behavior.go#L92
