### ISSUE TITLE
Thrift package has vulnerabilities

### ISSUE THREAD

**Issue by vmanikes-dd** [yarpc/yarpc-go#2196]
Hey guys

Looks like this package has vulnerabilities. Any reason we are using a version from 2016?
https://github.com/yarpc/yarpc-go/blob/dev/go.mod#L6

**Comment by biosvs** [comment]
Sorry for _a bit late_ response.

Probably, the question is about "github.com/apache/thrift". Yarpc doesn't use it directly anymore. The only place is end-to-end tests, where we're checking that yarpc may work with a servers created by a native apache thrift code.
