### ISSUE TITLE
Transport-specific error being leaked at rpc.Start()

### ISSUE THREAD

**Issue by breerly** [yarpc/yarpc-go#226]
Instead of transparently passing up any errors received during `rpc.Start`, we'll want to wrap it.

This might be a good time to introduce [pkg/errors](https://github.com/pkg/errors), or perhaps just do something similar.

A way to reproduce would be specifying the same port on 2 inbounds then calling start.

**Comment by breerly** [comment]
This can be moved to post-1.0 since errors during start result in application failure anyhow.

**Comment by kriskowal** [comment]
We have consensus that we won't use pkg/errors.

We also have consensus that all YARPC errors should be inspectable by behavior, e.g., `yarpc.IsUnrecognizedProcedureErorr(err)`.

I move that it is not important to provide an abstraction around Start/Stop errors.
