### ISSUE TITLE
Sample code to launch yarpc/tchannel server in a fx application

### ISSUE THREAD

**Issue by mlgupta** [yarpc/yarpc-go#2284]
Hi, I have been playing with yarpc with thrift and have been able to stitch together application that starts a yarpc server using tchannel protocol and thrift. The code basically looks like the following:
```
	tchannelTransport, err := ytch.NewTransport(ytch.ServiceName("myservice"), ytch.ListenAddr(*bind))
	if err != nil {
		log.Fatalln(err)
	}

	myInbound := tchannelTransport.NewInbound()
	dispatcher := yarpc.NewDispatcher(yarpc.Config{
		Name: "meeting",
		Inbounds: yarpc.Inbounds{
			myInbound,
		},
	})

	handler := NewMeetingHandler()
	dispatcher.Register(meetingserver.New(handler))

	if err := dispatcher.Start(); err != nil {
		fmt.Println("error:", err.Error())
	}

	fmt.Println("Server listening on", *bind)
	fmt.Println("Server listening on", tchannelTransport.ListenAddr())

	select {} // block forever
```

`NewMeetingHandler` defines handlers to be served by the server.

My thrift file is called `meeting.thrift`

While looking at the thriftrw generated code I saw a directory `meetingx`, and that piqued my interest. I assumed that I could use this to write fx application. And, I was able to write one, except for the fact that I am unable to define a yarpc/tchannel service in the fx application I wrote. Basically, this is what my code looks like: 
```
fx.New(
		fx.Provide(
			NewMeetingHandler,
			meetingfx.Server(),
		),
	).Run()
}
```
How can I initialize and use a yarpc/tchannel inbound in the fx application? I have not been able to find any sample code so far. Would appreciate any pointers in this regards.

**Comment by biosvs** [comment]
Hey @mlgupta,

> While looking at the thriftrw generated code

Do you mean thriftrw-plugin-yarpc? If so, `meetingfx.Server()` returns ServerResult ([example](https://github.com/yarpc/yarpc-go/blob/dev/encoding/thrift/internal/observabilitytest/test/testservicefx/server.go#L45)), which has 
```
[]transport.Procedure `group:"yarpcfx"`
```

Now you need another layer that will receive it and register in dispatcher, e.g.

```
type ServerStarterParams struct {
    fx.In

    Procedures [][]transport.Procedure `group:"yarpcfx"`
}

fx.New(
		fx.Provide(
			NewMeetingHandler,
			meetingfx.Server(),
                         CreateDispatcher(), // func that returns *yarpc.Dispatcher
		),
                fx.Invoke(func(d *yarpc.Dispatcher, p ServerStarterParams) {
                        for _, procedure := range p.Procedures {
                               dispatcher.Register(procedure)
                        }

	               if err := dispatcher.Start(); err != nil {
	               	fmt.Println("error:", err.Error())
	               }
                }),
	).Run()
}
```

Does it answer your question?

**Comment by mlgupta** [comment]
It does. I guess, the tricky thing to figure out here was how `[]transport.Procedure `group:"yarpcfx"`` got populated by fx and each element of it needed to be registered with dispatcher (your code shows that very clearly). TYSM, highly appreciated.
