### ISSUE TITLE
Combine Context & Meta

### ISSUE THREAD

**Issue by breerly** [yarpc/yarpc-go#23]
Let's try this out:

```
func (h Handler) Get(context Context, request Request) response, context, err
```

Will look more like node, python, & java.

**Comment by abhinav** [comment]
As per discussion, this is being abandoned.

For the record: Combining context and meta into request results in a very confusing API.

```
func GetValue(request *json.Request, body *GetValueRequest) (*GetValueResponse, *json.Response, error) {
    // ...
}
```

Where you have `Request` and `Response` objects conflating with the request and response objects that the user actually cares about.

It becomes weirder on the Thrift side:

```
... := thriftClient.SetValue(
    &thrift.Request{Context: ctx, ...}, key, value,
)
```

Where `thrift.Request` has a `Service` and `Method` parameter representing the Thrift service name and method, which users should not be able to modify. To work around that, you'd have to have yet another Request object which doesn't have a `Service`/`Method`/`Procedure`.

And if we use a single `yarpc.Request` object, it needs to have a `Procedure`, which again, users shouldn't have control over when it comes to the Thrift client, but should have control of when using the JSON or Raw clients.

The current API imposes a good separation of concerns between the different components of the request and we're going to keep it that way.

**Comment by abhinav** [comment]
Decided to give this a second go.
