### ISSUE TITLE
RFC: Apache Thrift Support

### ISSUE THREAD

**Issue by abhinav** [yarpc/yarpc-go#235]
For Apache Thrift/HTTP compatibility,

-   Request and response bodies must be enveloped.
-   Method name on the envelope must be just the name of the method, unless a
    multiplexed protocol is being used, in which case it must be a combination
    of the service name and the method name with a configurable delimiter.

Server
------

### Registration

Procedures will still be registered against the RPC object using the current
`$serviceName::$methodName` naming convention.

An enveloped HTTP Thrift request contains,

1.  Just the method name; or,
2.  Service name and method name with a configurable delimiter.

In the first case, we'll need to determine the service name somehow. This could
be via user-configurable HTTP request paths: `/foo` maps to `FooService`,
`/bar/v1` maps to `BarService`. In the second case, we already have enough
information to dispatch to `$serviceName::$methodName`. We can make all this
happen at handler registration time. Currently, Thrift handlers are registered
using this API.

```go
package thrift

func Register(registry transport.Registry, service Service)

// Usage:
//
// thrift.Register(rpc, myserviceserver.New(myHandler))
```

We can modify this API to support a variable number of options, using the
standard options pattern.

```go
package thrift

func Register(registry transport.Registry, service Service, opts ...Option)

// Only one of the following may be specified
func HTTPPath(path string) Option
func HTTPMultiplex(delimiter string) Option
```

We'll still want reasonable defaults for the case when the user does not
specify any of these options. The most convenient option is: Allow exactly one
Thrift service to be registered with the defaults (panic at registration time
otherwise), and use that service name. This will suffice for most users. For
users with multiple Thrift services, they MUST pick one of these disambiguating
schemes for each service they register.

### Validation

Currently we validate that all requests over HTTP contain the standard RPC
headers: `Rpc-Service`, `Rpc-Caller`, etc. That restriction will have to be
loosened for Apache Thrift/HTTP requests somehow.

Client
------

Thrift clients are currently built using the `New` function generated in the
`*client` package for a Thrift service.

```go
package myserviceclient

func New(c transport.Channel) Interface

// Usage:
//
// client := myserviceclient.New(rpc.Channel("myservice"))
```

Similar to registration, we will modify the generated `New` function to accept
a variable number of options.

```go
package myserviceclient

func New(c transport.Channel, opts ...thrift.Option) Interface
```

The same options `HTTPPath` and `HTTPMultiplex` will apply.

-------------------------------------------------------------------------------

Thoughts? @yarpc/golang

**Comment by breerly** [comment]
I don't want to support Apache Thrift generated clients calling YARPC servers.

The only thing I think we should focus on is that YARPC clients can call Apache Thrift servers. This enables new clients to call existing servers, which is nice because we won't have to use generated thrifty clients anymore.

I think this has implications in your Validation section, and perhaps the Registration section as well.

**Comment by abhinav** [comment]
Makes sense. I think that significantly simplifies the server side work.

**Comment by abhinav** [comment]
With that restriction, I think this might be possible without adding any new APIs. I'm gonna close this issue for now.
