### ISSUE TITLE
Transport: Return response context

### ISSUE THREAD

**Issue by abhinav** [yarpc/yarpc-go#236]
Currently transports do not return response contexts. The API for outbounds is,

    Call(ctx context.Context, request *Request) (*Response, error)

The API for inbounds is,

    Handle(ctx context.Context, req *Request, resw ResponseWriter) error

Both of these APIs need to return the response context back, and the encoding clients and handlers need to connect these up.

**Comment by breerly** [comment]
cc @kriskowal

**Comment by kriskowal** [comment]
We need to thread context for both inbound and outbound, as a separate argument since that context needs to carry baggage from inbound request to outbound requests, from inbound responses to the outbound response.

```
ctx, resMeta, resBody, err := Call(ctx, reqMeta, reqBody)
```

I’m going to take this API change on if we have consensus.

**Comment by kriskowal** [comment]
Oh, I misapplied prior comment. The issue as @abhinav points out stands.

**Comment by abhinav** [comment]
No longer necessary since we don't return response context.
