### ISSUE TITLE
tchannel/inbound: Document that we allow *tchannel.Channel to already be listening

### ISSUE THREAD

**Issue by abhinav** [yarpc/yarpc-go#244]
We allow the Channel passed to `tchannel.NewInbound` to be already listening when `Start` is called. We should document that in godocs.

**Comment by kriskowal** [comment]
This has been done. https://github.com/yarpc/yarpc-go/blob/db4774be959e888bea4533f56087b285195610fd/transport/tchannel/inbound.go#L52-L60
