### ISSUE TITLE
Difficult to call self during integration test

### ISSUE THREAD

**Issue by breerly** [yarpc/yarpc-go#245]
For integration testing, a common desire will be to use a random port when listening, and to then configure an outbound for calling yourself. Currently, this isn't possible:

``` go
rpc := yarpc.New(
    "myservice",
    Inbounds: []transport.Inbound{
        tch.NewInbound(nil),
    },
    Outbounds: transport.Outbounds{
        "myservice": tch.NewOutbound(nil, tch.HostPort("127.0.0.1:7777")),
    },
)
rpc.Start()
```

In the above solution, `7777` is the wrong port, but it's not possible to get the random port created when start was called on the inbound...

Options:
- Create a tchannel ahead of time, call listen on it, and then use the listening port to configure the outbound
- Create an outbound after the fact and use it directly

None of these options are very satisfying...

**Comment by abhinav** [comment]
Related: https://github.com/yarpc/yarpc-go/issues/87

**Comment by kriskowal** [comment]
This is related to trouble @peter-edge has encountered in building multi-process integration tests that need to listen on 0 and cross-communicate the port. It is almost like cases like this need a placement and service discovery system to direct traffic to tasks on ephemeral ports.

How does Mesos hand-off a port to a task? Does it listen on 0, pass the address to the child process through an environment variable, expect the client to listen on the same port with SO_REUSEPORT, then at some point in the future release the socket?

**Comment by kriskowal** [comment]
I think we might solve this specific case by having transport.Inbound implement a method that returns a peer chooser for its own address.

```go
tch := tchannel.NewTransport()
tchIn := tchIn.NewInbound()
rpc := yarpc.New(
    "myservice",
    Inbounds: []transport.Inbound{tchIn},
    Outbounds: transport.Outbounds{
        "myservice": tchIn.Loopback(),
    },
)
rpc.Start()
```

**Comment by kriskowal** [comment]
I’ve asked our Mesos friends how they manage the hand-off of ports to tasks. They reserve a block of high ports just under the ephemeral range, like 30,000 and up and Mesos meters these out to tasks. I’ll make note on Peter’s get ports PR.

**Comment by peter-edge** [comment]
I thought our goal was to move everything to `net.Listeners` per our discussion on https://github.com/yarpc/yarpc-go/pull/866, I started working on this in https://github.com/yarpc/yarpc-go/pull/897

**Comment by breerly** [comment]
Closing based on @peter-edge's comment.
