### ISSUE TITLE
Thread context as separate argument and return

### ISSUE THREAD

**Issue by kriskowal** [yarpc/yarpc-go#247]
We need to thread context from call to call, so that baggage can infect the entire call graph. We can accomplish this by shadowing the ctx variable in scope. The RPC library can implicitly merge request and response contexts in all serial cases, and the openctx project provides a public API for merging parallel response contexts.

Serial:
```
func Procedure(ctx context.Context, yarpc.ReqMeta, req Req) (ctx context.Context, yarpc.ResMeta, res Res, err error) {
    ctx, aResM, aResB, err := Alice(ctx, aReqM, aReqB);
    // Alice, via YARPC, merges req and res baggage
    ctx, bResM, bResB, err := Bob(ctx, bReqM, bReqB);
    // Bob, via YARPC, merges req and res baggage.
    // We thread the response baggage through the final context,
    // returning it to YARPC.
    retrun ctx, pResM, pResB, nil
}
```

Parallel is the same except that we explicitly reduce the last-known context with the response context as the responses flow in. `ctx` is always the freshest context in scope.

If we have consensus, I’ll make the necessary changes.

**Comment by breerly** [comment]
Can you contrast that to the current design? What are the benefits?

```go
func [Procedure(reqMeta yarpc.ReqMeta, reqBody []bytes) (resBody []bytes, arpc.ResMeta, err error) {
    resBody, resMeta, err := raw.Call(yarpc.NewReqMeta(reqMeta.Context()), resBody)
    resBody, resMeta, err := raw.Call(yarpc.NewReqMeta(resMeta.Context()), resBody)
    return resBody, yarpc.NewResMeta(resMeta.Context()), nil
}
```

**Comment by kriskowal** [comment]
@breerly,

Using `ctx` as the freshest context in *all* positions is more likely to be accidentally correct and remain correct in the face of change. With the current design, the user needs to scan upward to find the name of the most recent response meta or request meta, then scan downward to revise the context used for the next request or response. They will need to refactor the next and prior call sites if they introduce or remove a call.

In the parallel case, the most current context is not necessarily a property of a prior request or response context, so the code will push you more in the direction of the `ctx` common variable as boilerplate.

```go
func Procedure(reqMeta yarpc.ReqMeta, reqBody []bytes) (resBody []bytes, arpc.ResMeta, err error) {
    ctx := reqMeta.Context()
    var wg sync.WaitGroup
    var mx sync.Lock
    for x := range y {
       wg.Add()
       go func() {
           resBody, resMeta, err := raw.Call(yarpc.NewReqMeta(ctx), resBody)
           mx.Lock()
           ctx := openctx.Join(ctx, resMeta.Context())
           mx.Unlock()
           wg.Done()
       }()
    }
    wg.Wait()
    return resBody, yarpc.NewResMeta(ctx), nil
}
```

Vs, going with the flow of the standard library:

```go
func Procedure(ctx context.Context, reqMeta yarpc.ReqMeta, reqBody []bytes) (ctx context.Context, yarpc.ResMeta, resBody []bytes, err error) {
    var wg sync.WaitGroup
    var mx sync.Lock
    for _, reqBody := range reqBodies {
       wg.Add()
       go func() {
           resCtx, resMeta, resBody, err := raw.Call(ctx, yarpc.NewReqMeta(), reqBody)
           mx.Lock()
           ctx := openctx.Join(ctx, resCtx)
           mx.Unlock()
           wg.Done()
       }()
    }
    wg.Wait()
    return resBody, ctx, yarpc.NewResMeta(), nil
}
```

**Comment by breerly** [comment]
I can buy that.

```go
func Procedure(ctx context.Context, reqBody []bytes, options ...yarpc.ReqMetaOptions) 
    (ctx context.Context, yarpc.ResMeta, resBody []bytes, err error) 
 {
   ...
}
```

**Comment by prashantv** [comment]
I like the idea of returning a `ctx`, threading through does look pretty good. The only issue is that it's a lot of response args. 3 already felt like a lot, 4 feels like too many, especially since most people probably won't care about response meta.

I'm not a big fan of the variadic arguments, it seems odd for some of the meta properties to be at the beginning, and some at the end. I think it's cleaner for them to be grouped together.

Another option is to put the per-hop headers on the context, and clear out the per-hop req meta object on the returned context. I'd imagine this looking like:

```go
ctx, res, err := client.Procedure(yarpc.ReqMeta(ctx, Timeout(time.Second)), "body")
```

or if you don't have any request-specific options,
```go
ctx, res, err := client.Procedure(ctx, "body)
 ```

This means more objects in context, but as long as still treat the context as immutable, it's not too bad.

**Comment by bombela** [comment]
For information here what the signature of a grpc method looks like:
```
func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
```
(https://github.com/grpc/grpc-go/blob/master/examples/helloworld/helloworld/helloworld.pb.go#L85
)

Obviously in this case, there is no return of the context (which I personally believe is a bad idea, as the body of the response is already there for returning stuff).

Applying this to yarpc would make our signatures look like this:
```
func (c *greeterClient) SayHello(ctx context.Context, name string, opts ...yarpc.CallOption) (*HelloReply, error)
```
Which I find simpler.

**Comment by prashantv** [comment]
For method arguments, grpc has an advantage over Thrift: there's always exactly one argument (which itself is a message). So the method always looks the same.

Since Thrift allows multiple arguments, I think having options at the end can get confusing since you could have:
```go
type Client interface {
  SayHello(ctx context.Context, name string, opts ...yarpc.CallOptions) (...)
  SayHi(ctx context.Context, name string, to string, helloOpts HelloOptions, opts ...yarpc.CallOptions) (...)
}
```

So when you look at a call, it could look like either:
```go
client.SayHello(ctx, "hello", yarpc.Timeout(4 * time.Second))
// or 
client.SayHi(ctx, "p", "fx", HelloOptions{...}, yarpc.Timeout(4 * time.Second))
```

The variable number of method arguments combined with a variable number of YARPC options seems confusing to me.

**Comment by abhinav** [comment]
Okay, based on this discussion, seems like what we're going for is:

Client-side:

```go
// JSON
client := json.New(...)
ctx, err := client.Call(yarpc.ReqMeta(ctx).Procedure("foo"), reqBody, &resBodyOut)

// Thrift without options
client := myserviceclient.New(..)
ctx, resBody, err := client.MyMethod(ctx, arg1, arg2)

// Thrift with options
ctx, resBody, err := client.MyMethod(yarpc.ReqMeta(ctx).Headers(...), arg1, arg2)

// Reading response headers
resMeta := yarpc.GetResMeta(ctx)
fmt.Println(resMeta.Headers)
```

Server-side:

```go
// Same for JSON or Thrift
func (myHandler) Foo(ctx context.Context, reqBody *GetValueRequest) (
  context.Context, *GetValueResponse, error,
) {
  // Reading request metadata
  reqMeta := yarpc.GetReqMeta(ctx)
  fmt.Println(reqMeta.Caller, reqMeta.Service, reqMeta.Headers)

  // No response headers:
  return ctx, &GetValueResponse{..}, ..
  
  // with response headers
  return yarpc.ResMeta(ctx).Headers(...), &GetValueResponse{..}, nil
}
```

Note that we pass `yarpc.{Req,Res}Meta(ctx)` in place of `ctx` only when we
want to specify options.

---

To make this happen, we'll probably have the following APIs:

```go
package yarpc

type ReqMetaContext interface {
  context.Context

  Procedure(string) ReqMetaContext
  Headers(Headers) ReqMetaContext
}

func ReqMeta(context.Context) ReqMetaContext

type ReqMetaData struct {
    Caller, Service, Procedure string
    Headers Headers
}

// This is used on requests contexts for incoming requests on a server
func GetReqMeta(context.Context) *ReqMetaData

type ResMetaContext interface {
  context.Context
  
  Headers(Headers) ResMetaContext
}

func ResMeta(context.Context) ResMetaContext

type ResMetaData struct {
    Headers Headers
}

// This is used on response contexts returned by outgoing requests.
func GetResMeta(context.Context) *ResMetaData
```

Thoughts?

**Comment by bombela** [comment]
Looks good except I really don't like returning the ctx (similar to returning a RepMeta right now which I set to nil all the time). Am I correct that returning the ctx is for backward baggage propagation and application response headers?

**Comment by abhinav** [comment]
Update: New proposed API

This is slightly more verbose than the previous option but it's safer because
it's more difficult for users to use it incorrectly.


Client-side:

```go
// JSON
client := json.New(...)
ctx, err := client.Call(
  yarpc.WithMeta(ctx, yarpc.ReqMeta{
    Procedure: "foo",
    Headers: ...,
  }),
  reqBody,
  &resBodyOut,
)

// Thrift without request options
client := myserviceclient.New(..)
ctx, resBody, err := client.MyMethod(ctx, arg1, arg2)

// Thrift with request options
ctx, resBody, err := client.MyMethod(
  yarpc.WithMeta(ctx, yarpc.ReqMeta{
    Headers: ...,
  }), arg1, arg2)

// Reading response headers
resMeta := yarpc.GetResMeta(ctx)
fmt.Println(resMeta.Headers)
```

Server-side:

```go
// Same for JSON or Thrift
func (myHandler) Foo(ctx context.Context, reqBody *GetValueRequest) (
  context.Context, *GetValueResponse, error,
) {
  // Reading request metadata
  reqMeta := yarpc.GetReqMeta(ctx)
  fmt.Println(reqMeta.Caller, reqMeta.Service, reqMeta.Headers)

  // No response headers:
  return ctx, &GetValueResponse{..}, ..
  
  // with response headers
  return yarpc.WithMeta(ctx, yarpc.ResMeta{Headers: ...}), &GetValueResponse{..}, nil
}
```

Note that we use `yarpc.WithMeta(ctx, ...)` in place of `ctx` only when we want
to pass options.

---

`yarpc` will expose the following:

```go
package yarpc

func WithMeta(context.Context, Meta) context.Context

type Meta interface {
    meta() // private method so that we control all implementations
}

type ReqMeta struct {
    Procedure string
    Headers Headers
}

func (ReqMeta) meta() {} // implements  Meta

type ResMeta struct {
    Headers Headers
}

func (ResMeta) meta() {} // implements  Meta

type ReqMetaData struct {
    Caller, Service, Procedure string
    Headers Headers
}

// This is used on requests contexts for incoming requests on a server
func GetReqMeta(context.Context) *ReqMetaData

type ResMetaData struct {
    Headers Headers
}

// This is used on response contexts returned by outgoing requests.
func GetResMeta(context.Context) *ResMetaData
```

-----

Extra: In both cases, we can add a little safety to the `json` and `raw` client
APIs by declaring a `yarpc.ContextWithMeta` and expecting that rather than
`context.Context`. This will ensure that the user doesn't accidentally pass in
a plain `ctx` without setting the procedure:

```
package yarpc

- func WithMeta(context.Context, Meta) context.Context
+ func WithMeta(context.Context, Meta) ContextWithMeta
+ type ContextWithMeta interface { context.Context; contextWithMeta() }
```
```
package json

type Client interface { Call(yarpc.ContextWithMeta, ....) }
```

**Comment by abhinav** [comment]
@bombela Yes, we need to return the context to support backwards propagation. The idea is that you will be able to do,

```
func (myHandler) SomeMethod(ctx context.Context, ...) (context.Context, ...) {
  ctx, ...  := someService.Call(ctx, ....)
  ctx, ... := anotherService.Call(ctx, ...)
  return ctx, ...
}

**Comment by bombela** [comment]
Do we have any usecases for backward propagation? For now I see lots of drawback with it:

 - API is more complicated, less intuitive
 - In Go it is easy to ignore the returned ctx, thus cutting the propagation chain by mistake
 - We need a way to merge the baggageswell, this increases the complexity of yarpc
 - Merging baggages must be able to work transparently across nodes, this likely means the merging strategy must be backward propagated as well, which increases the protocol overhead
 - The baggage becomes a global across services, which is likely to introduce interesting bugs as some baggage gets overridden down the stack in some cases but not others
 - To mitigate this we can offer a centralize vetoed definition of baggages that are allowed to be backward propagated. But non-updated nodes must still be able to process them, not sure how much complexity this would add.

**Comment by bombela** [comment]
As discussed with @abhinav I will keep the backward propagation problem to another issue. For now the goal is to use context.Context first class in the API.

**Comment by bombela** [comment]
Just writing down here the result of the latest discussion from the team. The way we are going is based on @abhinav's proposal, except we return a `yarpc.ResMeta` instead of a generic `context.Context`. This is because we don't plan to implement backward propagation of baggage unless somebody really fight for it with compelling use cases.

Client-side:

```go
// JSON
client := json.New(...)
// -- Here we wrap ctx inside a ReqMeta to add extra arguments.
resMeta, err := client.Call(yarpc.ReqMeta(ctx).Procedure("foo"), reqBody, &resBodyOut)

// Thrift without options
client := myserviceclient.New(..)
// -- Here the call uses the ctx directly, in proper Go style.
resBody, resMeta, err := client.MyMethod(ctx, arg1, arg2)

// Thrift with options
// -- We can always add extra options trough a ReqMeta
resBody, resMeta, err := client.MyMethod(yarpc.ReqMeta(ctx).Headers(...), arg1, arg2)

// Reading response headers is done trough the ResMeta returned from every call.
fmt.Println(resMeta.Headers)
```

Server-side:
```go
// Same for JSON or Thrift
func (myHandler) Foo(ctx context.Context, reqBody *GetValueRequest) (
  yarpc.CallResMeta, *yarpc.GetValueResponse, error,
) {
  // Reading request metadata
  reqMeta := yarpc.GetReqMeta(ctx)
  fmt.Println(reqMeta.Caller, reqMeta.Service, reqMeta.Headers)

  // Returning an error:
  return nil, nil, fmt.Error("crap")

  // Successful result without response headers:
  return nil, &yarpc.GetValueResponse{..}, nil
  
  // And with response headers:
  return yarpc.ResMeta(ctx).Headers(...), &yarpc.GetValueResponse{..}, nil
}
```

Note that we pass `yarpc.ReqMeta(ctx)` in place of `ctx` only when we want to specify call options from the client. On the other hand we return `yarpc.ResMeta(ctx)` in place of `nil` only when we want to specify result options from the server.

---

To make this happen, we'll probably have the following APIs:

```go
package yarpc

type ReqMetaContext interface {
  context.Context

  Procedure(string) ReqMetaContext
  Headers(Headers) ReqMetaContext
}

func ReqMeta(context.Context) ReqMetaContext

type ReqMetaData struct {
    Caller, Service, Procedure string
    Headers Headers
}

// This is used on requests contexts for incoming requests on a server
func GetReqMeta(context.Context) *ReqMetaData

// Note: ResMeta is not changed.
```

**Comment by bombela** [comment]
Following our even more recent discussion, we came up with the additional proposal to split ctx and reqmeta, keeping ctx for timeout and baggages only.

This would look somewhat like this:

Client-side:
```go
// JSON
client := json.New(...)
resMeta, err := client.Call(ctx, yarpc.NewReqMeta().Procedure("foo"), reqBody, &resBodyOut)

// Thrift without options
client := myserviceclient.New(..)
resBody, resMeta, err := client.MyMethod(ctx, nil, arg1, arg2)

// Thrift with options
resBody, resMeta, err := client.MyMethod(ctx, yarpc.NewReqMeta().Headers(...), arg1, arg2)

// Reading response headers is done trough the ResMeta returned from every call.
fmt.Println(resMeta.Headers)
```

Server-side:
```go
// Same for JSON or Thrift
func (myHandler) Foo(ctx context.Context, reqMeta* HandlerReqMeta, reqBody *GetValueRequest) (
  *yarpc.ResMeta, *yarpc.GetValueResponse, error,
) {
  // Reading request metadata
  fmt.Println(reqMeta.Caller, reqMeta.Service, reqMeta.Headers)

  // Returning an error:
  return nil, nil, fmt.Error("crap")

  // Successful result without response headers:
  return nil, &yarpc.GetValueResponse{..}, nil
  
  // And with response headers:
  return &yarpc.ResMeta{Headers: ...}, &yarpc.GetValueResponse{..}, nil
}
```

Note how we pass `nil` whenever we don't need to customize the `ReqMeta`, and how we always pass `ctx` as the first argument.

**Comment by bombela** [comment]
Context is now a separate argument, and we don't return it.
