### ISSUE TITLE
Rename top-level RPC object to RPC Plane

### ISSUE THREAD

**Issue by breerly** [yarpc/yarpc-go#251]
## The Problem

@bombela, being new to YARPC, brought up a really good naming smell when he was trying to understand all the objects at play and their responsibilities - 

> It took me awhile to get that the top-level RPC object was actually the YARPC context, that contained all the config needed to register procedures, create clients, and send/receive messages. I always think of an individual message when I hear RPC.

And he's not wrong, when people hear "RPC" they think about it used in the common context:

> In my application, I send RPCs to the users service on a 5 minute interval.

Within our group even, we've taken to calling it the **Top-level RPC Object** to disambiguate. 

I think we can do much better; calling it the **Top-level RPC Object** is a mouthful, and it isn't super obvious what that means. It's come to mean something for our team, but FX proved that the term will be confusing for newcomers to the system (and I agree).

I suggest we rename this term to something that:

- Is not yet used or overloaded
- Is immediately obvious 
- Fits the responsibility of the object better

## The Proposal

I'd like that name be **RPC Plane**. 

Look how this term brings clarity to the object model:

> The RPC Plane is the object used to configure your YARPC application; it hands RPCs to your Procedures, and it is used by Encoding Clients to send RPCs. The RPC Plane is what allows your application to be **Transport-agnostic**.

Now lets switch the term back to **top-level RPC** object:

> The Top-level RPC object is the object used to configure your YARPC application; it hands RPCs to your Procedures, and it is used by Encoding Clients to send RPCs. The Top-level RPC object is what allows your application to be **Transport-agnostic**.

Not nearly as clear. 

## In Practice

How will the RPC Plane affect clarity of code? Positively, I think:

```go
// First, create an RPC Plane. This object contains all the info
// necessary to send and receive RPCs.
plane := yarpc.NewPlane("myservice", ...)

// Next, register some Procedures. As RPCs come across 
// the RPC Plane, they are handed to your Procedures for processing
json.Register(plane, json.Procedure("hello", hello))

// Inversely, Encoding Clients use the RPC Plane to send RPCs
users := json.New(plane.Channel("users"))

// Finally, start the RPC Plane. This allows all the Plane's internals to initiate, 
// and creates space to "warmup" before RPCs start flying. Just think of starting 
// the RPC Plane like takeoff - no RPCs can be sent or received before this point.
plane.Start()
```

Note that the RPC Plane should never leave the `main`, instead, an app should be structured like so:

1. Configure an RPC Plane in `main` (either by hand or with help from YAML)
2. Create Encoding Clients for every service you wish to talk to
3. Register Procedures and Handlers
4. Inject Encoding Clients into the parts of your application that needs them.

---

I'm open to different terms, but I do want to get away from this:

```go
rpc := yarpc.New("myservice", ...)
```

Thoughts?

**Comment by akshayjshah** [comment]
Completely agree with the problem statement, but I'm not 100% sold on "plane." Did you discuss using "server" instead?

**Comment by breerly** [comment]
I actually started with "server" first, but thought that would be confusing when there were no handlers, eg YARPC being used in client-only mode.

I ended up on RPC Plane because I thought it best described the "thing that allows your app to send and receive RPCs" even if you have a clien-only use-case.

I'm open to new terms, but I'd like them to be clear for server-only and client-only usecases.

**Comment by abhinav** [comment]
Sounds good to me. I'm okay with Plane if we don't have anything better. I think once the term settles in, it won't be confusing for users and they'll still be able to talk about it unambiguously.

**Comment by prashantv** [comment]
Agree that "server" can be confusing, but "plane" is not a common term when it comes to RPCs:
https://www.google.com/#q=rpc+plane

I'd prefer a more familiar term if we can find one.

**Comment by akshayjshah** [comment]
Yeah, I didn't consider the client-only use case :hurtrealbad: `plane` is fine, but let's keep trawling for a more familiar term.

Off the cuff:
- dispatcher
- interconnect
- interchange
- hub
- mux (anymux? universalmux?)
- RPCFoo, where Foo is one of the above

**Comment by prashantv** [comment]
Dispatcher is great, as is mux (Go uses `DefaultServeMux` so it wouldn't be completley unfamiliar).

The RPC object is basically dispatching between outbounds/inbounds, and is a word that doesn't need as much explanation, I like it

**Comment by breerly** [comment]
Mux is also not terrible:

```
mux := yarpc.NewMux("myservice", ...)

// create clients
users := usersserviceclient.New(mux.Channel("users")

// register handlers
thrift.Register(mux, myHandler{})

mux.Start()
defer mux.Stop()
```

I wonder if Mux has come to have a server relationship... that would confuse client-only uses.

**Comment by abhinav** [comment]
Dispatcher works better than Mux IMO

**Comment by bombela** [comment]
RPC plane or Dispatcher works for me. As long as we have something else than RPC that hopefully doesn't collide with another thing.

**Comment by kriskowal** [comment]
Dispatcher.

**Comment by bombela** [comment]
After thinking more about it, a better name might simply be "NewService()" and we can introduce a client only "NewClientOnly()".

Focusing on "NewService()" for now.

Let's see what this feels like:
```go
myservice := yarpc.NewService("my_service_routing_key", inbounds..., outbounds...)

myhandler := blabla...
thrift.Register(myservice, myThriftServer.New(myhandler))
thrift.Register(myservice, myThriftAdminServer.New(myadminhandler))

// start accepting requests...
if err := rpc.Start(); err != nil {
    log.Fatal(err)
}

// Assuming "other_service_routing_key" was registered as an outbound.
myClient := mythiftclient.New(myservice.channel("other_service_routing_key"))
healthStatsClient := mythifthealthstatsclient.New(myservice.channel("other_service_routing_key"))

})
```

And a pure client could look like:
```go
plane := yarpc.NewClientContext(outbounds...)

// start the machinery...
if err := rpc.Start(); err != nil {
    log.Fatal(err)
}

// Assuming "other_service_routing_key" was registered as an outbound.
myClient := mythiftclient.New(plane.channel("other_service_routing_key"))
healthStatsClient := mythifthealthstatsclient.New(plane.channel("other_service_routing_key"))

})
```

Nothing is set in stone.

**Comment by prashantv** [comment]
Given the dispatcher examples compared to the server/client examples, I think `Dispatcher` is clearer and has a couple of advantages:
 - Dispatcher accurately describes the object. Server, client, and plane can mean a lot of different things. I really don't like the line `plane := yarpc.NewClientContext(...)` - we're going to have the concept of clients when you create a Thrift client, we already have a very unrelated use of the word context, and `plane` kind of comes out of nowhere.
 - Less API. I'm a fan of reducing API surface area where possible
