### ISSUE TITLE
Client should yield a timeout error when server reaches deadline

### ISSUE THREAD

**Issue by bombela** [yarpc/yarpc-go#252]
Consider the following situation:
 - client build a request context with a deadline of X
 - client calls server method with the context
 - server is doing stuff that reaches the original deadline

We have to possible cases when we reach the deadline:
 - the client reaches it first, and gets a timeout error
 - the server reaches it first, and return a timeout error

Right now when the server returns context.Err(), the client receives an unexpected error! not a timeout error!!!

yarpc should understand this, and return a timeout error, because after all, this is a timeout error linked to the same context.

**Comment by prashantv** [comment]
+1, you'll see this kind of logic littered throughout tchannel-go:
```
	if err := mex.ctx.Err(); err != nil {
		return GetContextError(err)
	}
```
https://github.com/uber/tchannel-go/blob/a0e9cd019467c647d2ce0ed2cd7698b9ab589de2/mex.go#L107

We'll probably want the same thing in yarpc-go everytime the context error is checked.

`yarpc-go`'s tchannel transport will need to similarly handle `tchannel.ErrTimeout`

**Comment by abhinav** [comment]
Agreed. This was in the back of my mind during the original errors work but I guess I never wrote it down. TChannel already supports timeout error codes, so we just need to decide which HTTP status code we want to use for timeouts.

We currently use,

- 400 for `BadRequest`
- 500 for `Unexpected`

**Comment by breerly** [comment]
Perhaps `408 Request Timeout`?

**Comment by abhinav** [comment]
408 Request Timeout has a specific meaning: The client did not send the request while the server was waiting for it.

**Comment by breerly** [comment]
Perhaps we should always use `400` for all 400-range issues, and instead key off of a header for the specific error type...

**Comment by abhinav** [comment]
We should try to use only one strategy for resolving errors. We are already using status codes so we shouldn't add response headers on top. If we want to use response headers, we'll have to use that for BadRequest and Unexpected too.

FWIW, 504 gateway timeout seems close enough:

> The server was acting as a gateway or proxy and did not receive a timely response from the upstream server.

Another option is [CloudFlare's 524)(https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#CloudFlare) extension.

----

Aside: Are we in agreement that a timeout is a 500-range error? It's not user error.

**Comment by abhinav** [comment]
FWIW we already plan on using status code 429 for rate limiting errors.

**Comment by breerly** [comment]
> Aside: Are we in agreement that a timeout is a 500-range error? It's not user error.

Hmmm... I think I can buy that. Part of me feels like "who initiated the timeout" -

If the client says "respond in 1 second" with a deadline, and the server doesn't, is it the servers fault? Feels like a gray area, perhaps 4xx.

If the server imposes a timeout on itself that it can fulfill, that feels like a 5xx.

**Comment by breerly** [comment]
Actually, I'm onboard with a `504` as long as we don't need to differentiate between a client-initiated timeout and a server self-imposed timeout. 

Basically, these 2 situations will look identical:

* Client says "respond in 200ms", server can't comply: `504`
* Client says "respond in 10s", server has self-imposed 100ms timeout and can't respond in time: `504`

**Comment by bombela** [comment]
just to clarify @breerly, In the first case:
> Client says "respond in 200ms", server can't comply: 504

Do you mean the client gave up waiting and returns a timeout error to the user code directly? Because this is handled properly right now. And it could not possibly have an http error code as this stays at the client side.

**Comment by bombela** [comment]
Just to add to the topic, here is an example of what happens without merge the two kind of timeout:

I have a client calling a long-polling function on the server. The client sets the timeout to 15s. The server method being a good citizen takes care of respecting this timeout in order to cleanup unused resources.

Notice below that 2 times, the client gave up on the server returning anything, and returned a timeout error to my user code. The 3rd time the server reached the timeout a tad earlier than the client, and returned an unexpected error containing the details about the timeout. Obviously my client cannot recover from an unexpected error like that since it could be any other possible error.
   
```
2016/07/11 10:06:51 Ignoring timeout timeout for procedure "Broker::poll" of service "broker" after 14.9999726s
2016/07/11 10:07:06 Ignoring timeout timeout for procedure "Broker::poll" of service "broker" after 14.999974968s
2016/07/11 10:07:21 UnexpectedError: error for procedure "Broker::poll" of service "broker": context deadline exceeded
```

**Comment by kriskowal** [comment]
Communicating a timeout error with 504 Gateway Timeout or TChannel TimeoutError then normalizing to a common YARPC timeout error sounds good to me. The message should capture the breadcrumbs to the service that timed out, but must be informative-only/non-normative since there’s clearly a local vs remote timeout race.

**Comment by bombela** [comment]
What about:
	StatusRequestTimeout               = 408
