### ISSUE TITLE
Outbounds: Stateful outbounds scoped to a single request

### ISSUE THREAD

**Issue by abhinav** [yarpc/yarpc-go#260]
Right now outbounds are stateless. That is, `out.Options()` is expected to return the same thing at all times, and those options will apply to all calls for `out.Call`.

This makes it impossible for us to write a stateful outbounds (like a load balancing outbound) because there's no guarantee that `out.Options` is returning the same options as the outbound in `out.Call`.

    out := LeastRequestOutbound(out1, out2, out3)
    // where out1 is TChannel, out2 is HTTP, and out3 is some other transport

We could modify the `Outbound` interface to define a per-request scope.

    type Outbound interface {
        // ... start and stop as we already have

        NewCall() OutboundCall
    }

    type OutboundCall interface {
        Options() Options
        Call(ctx context.Context, request *Request) (*Response, error)
    }

This will allow a load balancing outbound to pick an outbound per-request and start a call on that.

**Comment by breerly** [comment]
For load balancing, I imagine a policy being [passed into the transport](https://github.com/yarpc/yarpc/blob/master/peers.md) from the dispatcher, which means the load balancing implementation itself would reside *in* the transport.

This makes me wonder if we actually need stateful outbounds - can we think of any other use-cases for stateful outbounds outside of load balancing and fallback?

**Comment by abhinav** [comment]
That load balancing policy applies only to multiple peers on the same outbound. We need some sort of stateful outbounds to handle load balancing across N outbounds of different types.

**Comment by breerly** [comment]
I can buy that. The proposed API isn't too bad either. +1

**Comment by prashantv** [comment]
+1 This looks good to me.

**Comment by abhinav** [comment]
Update: The current proposal has a couple problems:

-   Semantics of OutboundCall unclear. Would we allow,

    ```go
    call := out.NewCall()
    res1, err := call.Call(ctx, req1)
    res2, err := call.Call(ctx, req2)
    ```
    What are the semantics there? Are multiple requests for a single call
    guaranteed to go through the same underlying transport? That sounds like
    it's conflating the concept of a OutboundCall and an Outbound.
    
    And if we restrict `OutboundCall`s to a single `Call` each, we end up with
    an API which is very easy to use incorrectly. Seeing as this wouldn't
    really be an error that's recoverable at runtime, it would have to be a
    panic.

-   Middleware API gets decidedly more complex because `Filter`s are currently
    stateless but are expected to implement,
    
    ```go
    Call(ctx context.Context, request *Request, out Outbound) (*Response, error)
    ```

---

After discussing this with @kriskowal, there's another solution:

Our encoding-specific clients currently pull the outbound from `Channel`s at
construction time.

```go
package json

func New(ch transport.Channel) Client {
  return client{Outbound: ch.Outbound, ...}
}
```

Instead, we will change `Channel` to offer a `GetOutbound` function (better
names welcome) and have encoding-specific clients pull the outbound per-
request.

```go
package json

func (c *client) Call(...) ... {
    out := c.channel.GetOutbound()
    // ...
}
```

This is similar to the currently proposed change but instead of moving the
outbound selection one level deeper, we move it one level higher.

We'll also change the `Channel` from a plain struct to an interface.

```go
package transport

type Channel interface {
    Caller() string
    Service() string
    
    GetOutbound() Outbound
}

func SimpleChannel(caller, service string, outbound Outbound) Channel

func RoundRobinChannel(caller, service string, outbounds []Outbound) Channel
```

Note that users won't usually interact with the Channel constructors directly
because they will use `Dispatcher.Channel`.

```go
dispatcher.Channel("myservice")
```

----

This new design solves the previously mentioned problems.

-   The semantics for `GetOutbound()` are clear: You get a specific outbound.
    That outbound is re-usable. You can send as many requests through it as
    you want.
-   Middleware API remains the same. Filters are still scoped to a single
    request and outbound. If a filter needs to retry against a different
    outbound, that needs to happen at higher level middleware if/when that is
    implemented.

Thoughts? CC @yarpc/golang

**Comment by prashantv** [comment]
👍  This sounds good to me, keeps the middleware API simple and doesn't add a lot of extra API surface.
