### ISSUE TITLE
Yab --health check to HTTP doesn't work

### ISSUE THREAD

**Issue by breerly** [yarpc/yarpc-go#273]
We aren't installing the `meta::health` endpoint. 

```
$ yab -p http://localhost:6320 demo-yarpc-go --health
Failed while making call: HTTP call got non-success response code: 400
```

Could be we wan't to handle health checks differently, just taking note of this.

cc @prashantv

**Comment by kriskowal** [comment]
We have elected to solve this in another castle. cc @bombela
