### ISSUE TITLE
http/outbound: Make timeout and other parameters configurable

### ISSUE THREAD

**Issue by abhinav** [yarpc/yarpc-go#276]

**Comment by kriskowal** [comment]
@abhinav I’m adding this to the post 1.0.0 triage milestone since it’s a nice to have.

**Comment by abhinav** [comment]
For more context, this is specifically referring to the Dialer timeout, TLS Handshake timeout, etc. configured here: https://github.com/yarpc/yarpc-go/blob/37bfeae9088fe8a23f9a3def8c33d57e5e901f6c/transport/http/transport.go#L103-L109

**Comment by abhinav** [comment]
This is a nice to have but we haven't needed this so far. I'm going to close this until we decide we need this.
