### ISSUE TITLE
Pin to thriftrw-go >= 1, < 2

### ISSUE THREAD

**Issue by breerly** [yarpc/yarpc-go#309]
In order to cut a `1.0.0` of yarpc-go, we need our dependencies to be commit to their APIs so that we can relax the constaints on them to `>= 1, < 2`.  Because thriftrw-go is currently in release `0.1.0`, we need to work on stabilizing it soon.

Pinning to a more relaxed constraint during thriftrw's `0.x.y` is not an option because that could mean letting breaking changes in to yarpc customers.

**Comment by breerly** [comment]
Created a issue on thriftrw-go to define a 1.0.0 Milestone so we can quantify what's holding us back from committing to the current API.

https://github.com/thriftrw/thriftrw-go/issues/204

**Comment by kriskowal** [comment]
@abhinav is close to cutting a thriftrw 1.0.0. There will be some changes rolling into YARPC to accommodate it next week, then we can pin.

**Comment by breerly** [comment]
This is solved in dev.
