### ISSUE TITLE
Enforce strict service name validation

### ISSUE THREAD

**Issue by breerly** [yarpc/yarpc-go#313]
I'd like to enforce that all service names contain only:
- lowercase letters, i.e. `a-z`
- numbers, i.e. `0-9`, not appearing at the beginning of the service name
- dashes, i.e. `-`, not appearing at the beginning or end of the service name

In addition, the service name cannot be a:
- standalone number
- UUID
- a date or time

This means:
- no capitals
- no unicode
- no spaces
- no special characters
- no underscores
- no UUIDs

For example, the following service names would be valid:
- `super-skipper`
- `superskipper`
- `superskipper83`

While the following would not:
- `superSkipper`
- `SuperSkipper`
- `super_skipper`
- `083superskipper`
- `茶`
- ` `
- `super skipper`
- `26695a10-a384-48e7-8867-6d48b7fae80a`
- `100`
- `10-09-2016`

cc @yarpc/golang

**Comment by blampe** [comment]
I propose a rule to explicitly forbid anything that looks like a UUID :)

**Comment by breerly** [comment]
@blampe sure, that's actually a good idea. Since this is on startup, we can afford a bit more expensive checks.

**Comment by breerly** [comment]
@blampe I updated the rule to disallow standalone numbers and UUIDs - does that look better?

**Comment by malandrew** [comment]
Are there good uses for even allowing numbers?

**Comment by blampe** [comment]
foo-v2

**Comment by alsamylkin** [comment]
Should we disallow dots too? E.g. reading ports from configs could be confusing "service.v2.port", is v2 a transport or something else?

**Comment by blampe** [comment]
Let's try to move discussions to an issue if there's anything we need to follow up on re: naming.
