### ISSUE TITLE
Typo in panic string

### ISSUE THREAD

**Issue by mhamrah** [yarpc/yarpc-go#314]
When playing with yarpc-go I got a panic from the following line:

https://github.com/yarpc/yarpc-go/blob/84c0adb8fc5f205c031c336e4c152ede37e327fa/encoding/json/register.go#L160

This is most likely a type, and should be 'third'. The panic was caused by using  `required string` as a parameter in a service:

```
service Query {
    SomeResult SomeMethod (1: required string id)
}
```

This generates an interface method signature of `func SomeMethod(ctx context.Context, reqMeta yarpc.ReqMeta, id string) (*someservice.SomeResult, yarpc.ResMeta, error)`

Although I know it's more pragmatic to use request structures for thrift services (and this solves the problem) it seems like this is something that should be supported.

Although I know it's more pragmatic to use request str

**Comment by kriskowal** [comment]
This typo appears to have been fixed. @mhamrah @abhinav please open an issue against thriftrw if we need further changes regarding the generated code.
