### ISSUE TITLE
Outbound transports should return an error if the encoding is not specified.

### ISSUE THREAD

**Issue by kriskowal** [yarpc/yarpc-go#319]
They currently tolerate this case. Inbounds enforce it. We can terminate early with the same error we would get off the wire.

**Comment by breerly** [comment]
@kriskowal that means we can add this post 1.0 right? Let's take it off this milestone if that's the case.

**Comment by abhinav** [comment]
We already do this if the outbound was obtained from the Dispatcher:

- https://github.com/yarpc/yarpc-go/blob/dev/dispatcher.go#L108
- https://github.com/yarpc/yarpc-go/blob/dev/internal/request/validator_outbound.go#L42
- https://github.com/yarpc/yarpc-go/blob/dev/internal/request/validator.go#L111
