### ISSUE TITLE
All transports must support multiple hostports

### ISSUE THREAD

**Issue by breerly** [yarpc/yarpc-go#326]
Currently the HTTP transport only takes one hostport - we need _every_ transport to support 1 or more hostports. This will enable other features like load balancing, peer selection, etc...

Not having this from day one means we'll be forced to break the API later.

**Comment by kriskowal** [comment]
@willhug can have the honor of closing this ticket soon.

**Comment by kriskowal** [comment]
Punting this to post-1.0. Instead, we will ensure that we can introduce support for peer choosers in TChannel after 1.0 without breaking the interface. This means renaming the TChannel outbound constructor to make room for the grown up constructor post-1.0.  #521

**Comment by kriskowal** [comment]
TChannel now supports peer choosers, in addition to HTTP.
