### ISSUE TITLE
Dynamic outbound selection

### ISSUE THREAD

**Issue by abhinav** [yarpc/yarpc-go#328]
Currently we maintain a `map[string]Outbound` mapping for outbounds. This
makes it impossible for someone to dynamically build outbounds based on the
service name. Perhaps we should allow injecting an interface with the
following method:

```
GetOutbound(service string) Outbound
```

**Comment by breerly** [comment]
This might be necessary for #329

**Comment by abhinav** [comment]
`map[string]Outbound` is config level only. We can switch it to an interface (with support for overrides) internally later.

**Comment by abhinav** [comment]
This is taken care of by [ClientConfigProvider](https://godoc.org/go.uber.org/yarpc/api/transport#ClientConfigProvider).
