### ISSUE TITLE
By-RPC-Type Outbound

### ISSUE THREAD

**Issue by breerly** [yarpc/yarpc-go#329]
Some transports will only support one of the 5 RPC types:
- Unary
- Oneway
- Downstream
- Upstream
- Duplex

A Kafka transport, for example, would only support Oneway RPCs. 

Configuring all calls to Service X to use the Kafka transport might make it impossible to call a majority of Service X's procedures. Instead, you need to be able to configure a gradient of transports, such that you can make RPCs to all procedure types of the 5 listed above:

> When calling Service X, prefer Kafka for Oneway calls, and TChannel for Unary calls.

Once we have Oneway support for HTTP and TChannel (#327), then we should be able to build a Capability-based Outbound that enables the above usecase.

**Comment by kriskowal** [comment]
@AlexAPB will land a solution for Oneway vs Unary RPC that sets the precedent for this design soon.

**Comment by AlexAPB** [comment]
resolved #420
