### ISSUE TITLE
Automatic client instantiation

### ISSUE THREAD

**Issue by abhinav** [yarpc/yarpc-go#330]
A common pattern for using YARPC is,

```go
type myHandler struct {
    KeyValue keyvalueclient.Interface
    AnotherService anotherserviceclient.Interface
}

// and then

handler := myHandler{
    KeyValue: keyvalueclient.New(dispatcher.Channel("keyvalue")),
    AnotherService: anotherserviceclient.New(dispatcher.Channel("another")),
}
```

A problem with this, besides the stuttering, is that people often get lazy and
just inject the `dispatcher` in directly. They then call `Channel` at request
time, opening themselves up to `panic`s due to typos in the service name.

Perhaps we should use reflection to fill the clients in, getting the service
name from tags. For example,

```go
type myHandler struct {
    KeyValue keyvalueclient.Interface `service:"keyvalue"`
    AnotherService anotherserviceclient.Interface `service:"another"`
}

var h myHandler
thrift.InjectClients(dispatcher, &h)
```

Implementation-specific concern: `keyvalueclient.Interface` is an `interface`
so we'll need a way to map that type to a `New` function for it. We could
probably do that with some global state and an `init()` function in the
`keyvalueclient` package.

```go
package keyvalueclient

var typeOfInterface = reflect.TypeOf((*Interface)(nil)).Elem()

func init() {
    thrift.RegisterClient(typeOfInterface, New)
}
```

Thoughts?

---

Worth noting that another common pattern is,

```go
type myHandler struct {
    KeyValueGateway *KeyValueGateway
}

type KeyValueGateway struct {
    Client keyvalueclient.Interface
}
```

So we will want to fill these at arbitrary depth of public attributes.

CC @prashantv @kriskowal @breerly @bombela

**Comment by prashantv** [comment]
This definitely seems useful, although I don't know if it's something the `thrift` library should provide. Maybe a separator `injector` package? (It could also live outside of yarpc)

**Comment by abhinav** [comment]
Implementing this will most likely require a small change to code generation. We could make it a plugin, but that means people have to explicitly have code generated for it. I think this would make a nice "available by default" feature.

**Comment by abhinav** [comment]
Follow up: This functionality can be made non-Thrift specific but we still want it to live in the YARPC package. We don't want to write a generic dependency-injection library. This will be specific to instantiating clients based on service names.
