### ISSUE TITLE
transport.Request should support a bag of values

### ISSUE THREAD

**Issue by abhinav** [yarpc/yarpc-go#340]
We should allow transport.Request to hold a bag of values (similar to Context). This will allow for,

- Middleware that needs to pass per-request information down the call stack.
- More complicated transports and encodings; especially the case where there's some coupling between the two.

We'll need to figure out both, server and client side APIs. Worth noting that the bag of values WILL NOT be sent or received over the wire unless the component making use of it explicitly sticks it onto the attributes of the request that are sent over the wire (headers, etc.).

CC @mincai who expressed need for this.

**Comment by mhamrah** [comment]
My two cents: I think it would be better to keep request-scoped information as part of the context, and use the https://godoc.org/context#WithValue to set context-related information. Otherwise they'll be two places to achieve the same thing.

**Comment by breerly** [comment]
Agreed with @mhamrah :)
