### ISSUE TITLE
tchannel.Outbound has not been started or was stopped

### ISSUE THREAD

**Issue by AlexAPB** [yarpc/yarpc-go#341]
If you have a client-only Dispatcher and try to make a request through it without calling `Start()` you get the error:

```
panic: tchannel.Outbound has not been started or was stopped

goroutine 1 [running]:
panic(0x4d73c0, 0xc42038d3f0)
        /usr/local/Cellar/go/1.7/libexec/src/runtime/panic.go:500 +0x1a1
[..]
```

It's not very obvious from this error that we should call `dispatcher.Start()`.

**Comment by kriskowal** [comment]
We’ve evolved the lifecycle and outbound code around this problem. I'm not confident we've landed on the permanent solution, but for now, Choose() blocks using lifecycle.UntilRunning() or a timeout. We may need to revisit the particulars, but this issue has been solved.
