### ISSUE TITLE
yarpc.Config does not support multiple outbounds per service

### ISSUE THREAD

**Issue by abhinav** [yarpc/yarpc-go#344]
We will need to support this for things like:
- LoadBalancingChannel
- Capability based transports
- One-way and unary transports for the same service

**Comment by breerly** [comment]
Outbounds should be composable, so I'm not sure that we need to support multiple outbounds per service. 

Instead, I would expect every service to take only one outbound. That outbound *very well* might be `LoadBalancingOutbound(outbound1, outbound2)`.

**Comment by abhinav** [comment]
Outbounds can't be composable anymore because we decided to support stateful channels instead of stateful outbounds. See https://github.com/yarpc/yarpc-go/issues/260.

So the composiblity extension point is now provided by the Channel interface.

**Comment by breerly** [comment]
Outbounds are now composable!
