### ISSUE TITLE
Use pkg/context in public API

### ISSUE THREAD

**Issue by breerly** [yarpc/yarpc-go#362]
This reduces the dep footprint, something I'd like to focus on for a 1.0 release.

Note we should only do this when we know our customers have migrated to Go >= 1.7.

**Comment by sectioneight** [comment]
1.7 is the default in production. Any timeline on this?

**Comment by breerly** [comment]
Weeks not months, just want to make sure we don't have any customers still on 1.6 :)

**Comment by breerly** [comment]
Turns out this isn't easily doable - for some reason you can't pass in `pkg/context` to TChannel since it relies on a `golang.org/x/net/context`.

Since relying on `golang.org/x/net/context` is the safest answer to this problem, I'm inclined to go 1.0 without removing that dependency.

Obviously Go needs to figure this out - the current situation means that noone can migrate to `pkg/context`.

**Comment by abhinav** [comment]
reopening because #394
