### ISSUE TITLE
Customize HTTP headers

### ISSUE THREAD

**Issue by abhinav** [yarpc/yarpc-go#367]
Outbounds support application headers but for transports like HTTP, I think we
want users to be able to customize the HTTP headers on a global basis.

For example, consider the scenario where a user wants an auth signature of
some kind (`X-Signature: $something`) to all outgoing HTTP requests.

**Comment by kriskowal** [comment]
Punting to post 1.0.0 triage.

**Comment by Motiejus** [comment]
+1 on this.

We would like to set XPR headers for outgoing HTTP YARPC calls, and would highly appreciate this feature.

**Comment by abhinav** [comment]
@Motiejus This issue doesn't solve your problem. This issue is pretty much
moot at this point because the original proposal would break the contract
YARPC HTTP services hold with each other. We can't do that; services are
already in production that are relying on this contract. I'll be closing this
issue.

What you want is the ability to set a specific HTTP header in addition to the
YARPC headers being sent over the wire. Please create a separate issue for
that.

Thanks!
