### ISSUE TITLE
Consolidate {json,thrift,raw}.Register

### ISSUE THREAD

**Issue by abhinav** [yarpc/yarpc-go#379]
Currently, registration looks like,

```
json.Register(dispatcher, json.Procedure("foo", myJsonFunction))
raw.Register(dispatcher, raw.Procedure("bar", myRawFunction))
thrift.Register(dispatcher, keyvalueserver.New(myHandler{}))
```

I think we can consolidate this into either a `yarpc.Register(dispatcher, ...)` or `dispatcher.Register(...)`.

```
yarpc.Register(dispatcher, json.Procedure("foo", myJsonFunction))
yarpc.Register(dispatcher, raw.Procedure("bar", myRawFunction))
yarpc.Register(dispatcher, keyvalueserver.New(myHandler{}))

// Or

dispatcher.Register(json.Procedure("foo", myJsonFunction))
dispatcher.Register(raw.Procedure("bar", myRawFunction))
dispatcher.Register(keyvalueserver.New(myHandler{}))
```

The only thing the encoding-specific register functions do is wrap the user-
defined handler into a transport-level handler. This can be done in the
corresponding `Procedure` functions (in case of Thrift, the `$server.New(..)`
function).

----

### Implementation Notes

We can implement `yarpc.Register` or change `transport.Registry.Register` to
accept a `[]Registrant` or similar.

```
type Registrant struct {
    Service string
    Procedure string
    Handler Handler
}
```

And that has the same information needed by the current `dispatcher.Register`
function. Then we simply modify `json.Procedure`, `raw.Procedure`, etc. to
return a `[]Registrant`.

**Comment by breerly** [comment]
Seems reasonable 👍
