### ISSUE TITLE
Return error on outbound calls if Dispatcher wasn't started

### ISSUE THREAD

**Issue by breerly** [yarpc/yarpc-go#380]
Currently a user might get a cryptic failed request when making outbound calls, and the underlying reason may very well be that the Dispatcher wasn't actually started. This actually tripped up @abhinav and @apeatsbond during pairing.

This should be trivial to track and check during outbound calls.

**Comment by abhinav** [comment]
Turns out that our outbounds already panic if they weren't started. The issue
was that if the dispatcher failed to start because of an inbound, it would
still leave the outbound running. The fix is to stop anything that was started
if any other start failed.
