### ISSUE TITLE
transports: Make Start idempotent

### ISSUE THREAD

**Issue by abhinav** [yarpc/yarpc-go#381]
We should make the Start methods on transports idempotent so that we can call
`Start()` on them in advance before building the `Dispatcher` and calling
start. Besides being extra safe, this allows simplifying some of our tests so
that they can listen on port 0 and build a dispatcher that can call itself.

```
inbound := http.NewInbound(":0")
require.NoError(t, inbound.Start())

yarpc.NewDispatcher(yarpc.Config{
    // ...
    Inbounds: transport.Inbounds{inbound},
    Outbounds: transport.Outbounds{
        "self": http.NewOutbound(inbound.Addr().String()),
    },
})
```

**Comment by abhinav** [comment]
Okay, so maybe this isn't right. `Start()` for inbounds takes the
`ServiceDetail` and `Deps` as arguments. I dislike the undefined behavior we
will have if `Start` gets called with different `ServiceDetail`s multiple
times if we try to make it idempotent. Additionally, for both, inbounds and
outbounds, we'll have to ignore the `Deps` if the functions are called
multiple times.

If we're trying to address the [call-self use case](https://github.com/yarpc/yarpc-go/commit/e2b213e0a0f01f259f2bb137505fb557c382436d#diff-c11198611f93b93a248208cbc6f4d0feR115)
for tests, maybe we can get away with adding support for adding outbounds to
`Dispatcher` after `Start()`ing?

**Comment by abhinav** [comment]
Thoughts? @breerly @kriskowal @prashantv

**Comment by breerly** [comment]
@abhinav I'd rather that as well.

**Comment by bombela** [comment]
Adding after the fact feels uneasy, things are now mutable everywhere.

#### What about a special kind of "loopback" outbound?

```
inbound := http.NewInbound(":0")

yarpc.NewDispatcher(yarpc.Config{
    // ...
    Inbounds: transport.Inbounds{inbound},
    Outbounds: transport.Outbounds{
        "self": transport.LoopbackOutbout(http.NewOutbound, inbound),
    },
})

#### What about a Listen() and Start()

**Comment by breerly** [comment]
To @bombela's point - it is nice that the dispatcher is immutable.

**Comment by abhinav** [comment]
Based on the discussion above and offline, the consensus seems to be that this
is really hard to do "right" and the value provided by it isn't worth the
effort.

We can invest more into a call-self approach with something like a
LoopbackOutbound if we find that we need services to be able to call
themselves directly. Right now this is used for tests only.

FYI to implement a loopback outbound, we would need inbounds that support that
to implement a function which builds an outbound to talk to that inbound.
Something like,

    type Loopbacker interface {
        Inbound
    
        LoopbackOutbound() (Outbound, error)
    }
    
We can investigate this more if we need this, but for now I'm closing this
issue.
