### ISSUE TITLE
Decide on HTTP wire format

### ISSUE THREAD

**Issue by breerly** [yarpc/yarpc-go#39]
Let's decide on the wire format for HTTP - this came up from #30, where we @abhinav didn't want to see `YARPC-Ttlms`.

**Comment by kriskowal** [comment]
I’ll start a PR to doc the protocol on the yarpc.io repo.

**Comment by kriskowal** [comment]
See https://github.com/yarpc/yarpc.io/pull/4

**Comment by breerly** [comment]
looks like we're good here
