### ISSUE TITLE
[PeerList] Move Control of Calling Downstreams into Peers

### ISSUE THREAD

**Issue by willhug** [yarpc/yarpc-go#423]
Our first version of the PeerList/PeerProvider functionality had Peers as standalone objects that had very little information associated with them.  Unfortunately in order to get information to do a downstream call we had to cast those peers (and the peer's peeragent) to get the juicy Http objects underneath.

A solution to this is to invert the control back into the Peer.  So, an http.Peer would look like this:

```
HTTPPeer struct {
  hostport.PeerIdentifier
...
}

(p *HTTPPeer) CallOneway { // Implements OnewayCallable
(p *HTTPPeer) CallUnary { // Implements UnaryCallable
```

Then, in the http.Outbound, we'd call into the PeerlIst to get the transport.Peer and cast it to whatever downstream we wanted to use (OnewayCallable, UnaryCallable).  Under the hood, we should have a guarantee that the http.Outbound is dealing with HTTPPeers (we can enforce this in the outbound through the agent if we want).  This will also allow us to Wrap these peers (a bit haphazardly) by attempting to cast a peer to OnewayCallable/UnaryCallable and if that works, your wrapped peer will need to implement that interface.

**Comment by kriskowal** [comment]
Moving to post 1.0 triage since we will not block a release on this issue.

**Comment by kriskowal** [comment]
Moving to wishlist. It would be neat to eliminate the casting, and even better to be able to use a single peer as an outbound, instead of the SinglePeerList abstraction. Regardless, this is would-be-nice, and has no known customer impact.
