### ISSUE TITLE
[PeerList] Change Agent interface names?

### ISSUE THREAD

**Issue by willhug** [yarpc/yarpc-go#425]
Currently the Functions are Retain/Release Peer

@bombela mentioned potentially changing retain to GetOrCreate thoughts?  I'm amenable to slightly clearer interface names

@abhinav @kriskowal @AlexAPB

**Comment by kriskowal** [comment]
I’m a fan of the Retain/Release duals. GetOrCreate has merits, but its dual is PutBackAndMaybeDelete.

**Comment by kriskowal** [comment]
We are going to stick with Retain/Release.
