### ISSUE TITLE
Friendlier interface to raw encoding

### ISSUE THREAD

**Issue by abhinav** [yarpc/yarpc-go#43]
The transport level APIs need to be wrapped into a nicer API similar to JSON/Thrift encodings for Raw.

**Comment by breerly** [comment]
:balloon: :balloon: :balloon:

**Comment by abhinav** [comment]
Here's the interface I'm planning for this:

To make outgoing calls,

```go
client := raw.New(rpc.Channel("myservice"))

res, resMeta, err := client.Call(
	ctx,
	meta,
	&raw.Request{
		Procedure: "hello",
		Body: bytes.NewReader(payload),  // any io.Reader will do
		TTL: 42,
	},
)

if err != nil { ... }

defer res.Close()
... := ioutil.ReadAll(res)
```

To register a procedure,

```go

func Hello(ctx context.Context, m yarpc.Meta, req io.Reader, res raw.ResponseWriter) error {
	headers := res.Headers()
	headers['foo'] = 'bar'

	if err := res.Write([]byte("world")); err != nil {
		return err
	}

	return nil
}

// During registration:

raw.Register(rpc, raw.Procedure("hello", Hello))
```

This API is fairly similar to the low-level API, which itself is similar to the
`net/http` handler API.

Thoughts?

**Comment by breerly** [comment]
I think with the triples approach, that the request *is* the body, and everything else is either in meta or context. This approach looks a bit akward where a handful of the metadata is on the request, but the other is in `meta`.

**Comment by kriskowal** [comment]
This seems fine to me, particularly with readers and writers.

**Comment by prashantv** [comment]
Can you do a comparison of using the `raw` protocol vs the transport protocol.

Since json collapses meta and context, should `raw` do the same?

**Comment by abhinav** [comment]
I'm experimenting with the API a bit more. Hold off on this and I'll update the issue when I have something else.

**Comment by abhinav** [comment]
New API based on changes made in #50:

Calling:

	client := raw.New(channel)
	resBody, response, err := client.Call(
		&raw.Request{
			Context: ctx,
			Procedure: "submit",
		},
		[]byte{1, 2, 3},
	)

Registration:

	func Submit(req *raw.Request, reqBody []byte) ([]byte, *raw.Response, error) {
		// ...
	}

	raw.Register(rpc, raw.Procedure("submit", Submit))

Basically, the raw transport deals in `[]byte`s only. If streaming versions are required, users can use the low-level transport API.

**Comment by breerly** [comment]
Dude - this is awesome. :+1: :+1: :+1:
