### ISSUE TITLE
[PeerList] Alter Peer.Status() to return a peer.Status Pointer

### ISSUE THREAD

**Issue by willhug** [yarpc/yarpc-go#468]
currently the peer interface has the status function:

```
	// Get the status of the Peer
	Status() Status
```

We should switch it to

```
	// Get the status of the Peer
	Status() *Status
```

So we're not creating new status objects as we pass them around (currently this is specific to the hostport.Peer)

**Comment by willhug** [comment]
assigned to @abhinav to add some context

**Comment by kriskowal** [comment]
awaiting that context from @abhinav. My opinion is that returning a shallow copy avoids having to retain a lock on the peer state.

**Comment by kriskowal** [comment]
Closing unless compelling reasons come back. Getting close to 1.0.
