### ISSUE TITLE
[PeerList] Add extra options to the peer.Status

### ISSUE THREAD

**Issue by willhug** [yarpc/yarpc-go#469]
Currently the peer.Status only has ConnectionStatus and PendingCount, we should update it to have other fields such as:

```
chosenCount (number of times chosen)
numFailures (number of times failed)
```

Unfortunately these two numbers will be ever increasing, we should potentially change them or find some way we can consolidate the issues (maybe create a % success?)

**Comment by kriskowal** [comment]
Let’s prioritize for RC 3, @willhug

**Comment by kriskowal** [comment]
We can augment the status struct in future releases. Punting to post 1.0.

**Comment by peter-edge** [comment]
Is this still an issue?

**Comment by willhug** [comment]
closing for now, we can add anything we need in the future
