### ISSUE TITLE
[PeerList] Refactor Peer Start/Finish functions for Peers && Add finish closure to PeerLists

### ISSUE THREAD

**Issue by willhug** [yarpc/yarpc-go#472]
Peer Interface Old world:

```
StartRequest() (finish func())
```

Peer Interface New World:

```
StartRequest(Subscriber) // Subscriber is the subscriber that *Shouldn't* be notified
FinishRequest(Subscriber)  // Subscriber is the subscriber that *Shouldn't* be notified
```

PeerList old ChoosePeer func:

```
ChoosePeer(context.Context, *transport.Request) (Peer, error)
```

PeerList New ChoosePeer func:

```
// ChoosePeer should run the Peer.StartRequest and Peer.FinishRequest (through it's onFinish closure)
ChoosePeer(context.Context, *transport.Request) (p Peer, onFinish func(error), error)
```

This will allow the PeerLists to safely update their own internal state (within a lock) and remove the opportunity for a deadlock from the Notify.

**Comment by abhinav** [comment]
> ```
> StartRequest(Subscriber) // Subscriber is the subscriber that *Shouldn't* be
> notified
> FinishRequest(Subscriber)  // Subscriber is the subscriber that *Shouldn't* be notified
> ```

That's a weird interface. `StartRequest(Subscriber)` sounds like the complete
opposite of that.

**Comment by willhug** [comment]
This is half finished now after @kriskowal 's change.  The only change left is updating the `ChoosePeer` format to return the "on finish" method

**Comment by kriskowal** [comment]
Prioritizing for RC 3, @willhug
