### ISSUE TITLE
[PeerList] Allow ChoosePeer to have lower wait threshold for getting a peer

### ISSUE THREAD

**Issue by willhug** [yarpc/yarpc-go#476]
Currently, the Peer Selection logic of the RoundRobin Peerlist will wait until it has a Peer or the Context.Deadline is met.  This is unideal, in reality we want to be able to set a lower threshold for peer selection (or no threshold at all) in order to bubble the request back up to a higher level that could retry on a different outbound (or something else).  I'm not exactly sure how we would want this to work, so this task should be a bit more of a discussion.

Thoughts?

**Comment by kriskowal** [comment]
We can make this change without impacting the public interface of chooser.Choose, by canceling the context if it does not respond before a shorter deadline. Punting to post 1.0.

**Comment by kriskowal** [comment]
Let’s revive this if it becomes a problem for a customer.
