### ISSUE TITLE
[PeerList] Move Subscribers list lock to the Peer

### ISSUE THREAD

**Issue by willhug** [yarpc/yarpc-go#477]
Currently the Agent has a global lock across changes to every peer's subscribers, instead each peer should have it's own Lock for updating the subscriber list.

A caveat to this might be removing the Sub/UnSub from the Agent and putting it directly on the Peer Interface.

**Comment by kriskowal** [comment]
Punting to after 1.0 since it is an internal performance change.

**Comment by kriskowal** [comment]
I believe this has been addressed. Please revive if we need to revisit this.
