### ISSUE TITLE
[PeerList] Adjust names for Peer interfaces

### ISSUE THREAD

**Issue by willhug** [yarpc/yarpc-go#478]
The new world should look like this:
```
peer.Chooser interface {
  ChoosePeer(...)...
}

peer.List interface {
  Add(identifier)
  Remove(identifier)
}

Lifecycleable interface {
  Start() error
  Stop() error
}
```

We've split the Chooser a a higher level concept so we can simply pass that in directly into an outbound (instead of a PeerList which insinuates a list of peers).

**Comment by abhinav** [comment]
Just `Lifecycle`.

**Comment by kriskowal** [comment]
see #464 This should be Stopper.Stop. The Start() is irrelevant, since the pattern for using a manager would be something like a wait group.

```go
x.Start()
stopper.Add(x)

go func() {
   // ...
   stopper.Stop()
}()

stopper.Select() // blocks until all stoppers stop
```

**Comment by willhug** [comment]
Done except for the lifecycle stuff which is encompassed in #464
