### ISSUE TITLE
Rename Channel

### ISSUE THREAD

**Issue by breerly** [yarpc/yarpc-go#479]
Channel has always been confusing for customers, and I think it's because:

1. You configure YARPC by setting up a dispatcher
2. While doing that, you are presented with Outbounds, which is the map of service to Outbound objects
3. When you go to create a client, you suddenly are presented with this Channel concept

Instead of Channel, I wonder if this would be a better experience:

```go
// configure outbounds in a dispatcher
dispatcher := yarpc.NewDispatcher(yarpc.Config{
    Name: "myservice",
    Outbounds: yarpc.Outbounds{
        "popuworld": { Unary: http.NewOutbound() },
    },
})

// clients need outbounds to be configured
popuworldClient := popuworldclient.New(dispatcher.Outbound("popuworld"))
```

I think by using the Outbound concept to *connect* the config step and client creation step, you get a more clear experience.

**Comment by abhinav** [comment]
We can eliminate `Channel` and make `dispatcher.Outbound` return an `Outbound`
which wraps the real `Outbound` and punches in the `Caller` and `Service` into
all outgoing `Request`s. We could also do this wrapping once -- at build time.

**Comment by bombela** [comment]
I am for wrapping at build time, but it doesn't matter much, we can always change that without impacting the API.

Remove channel is going to be a fun renaming, this one might have collision with everything.
