### ISSUE TITLE
[PeerList] Allow introspection endpoints for peerlists/outbounds/inbounds/everything

### ISSUE THREAD

**Issue by willhug** [yarpc/yarpc-go#490]
In order to be able to see what's going on inside the PeerLists we should have the ability to introspect the running processes.

**Comment by kriskowal** [comment]
Prioritizing for RC 3.

**Comment by kriskowal** [comment]
@bombela please follow-up on this issue with status and direction. We should start reviewing your changes soon.

**Comment by breerly** [comment]
Resolved :)
