### ISSUE TITLE
[Responses] Look into converting CallResMeta and ResMeta into structs

### ISSUE THREAD

**Issue by willhug** [yarpc/yarpc-go#512]
The CallResMeta and ResMeta interfaces are currently used for return information from outbounds and inbounds respectively.  
Since these are interfaces, any changes to the api constitutes a breaking change.  For the CallResMeta this may not be a big deal because only Outbounds should be constructing a CallResMeta object (we'd break the APIs but we should be the only ones implementing the API anyway).  For ResMeta this may be an issue where an Inbound handler can return any object that implements the ResMeta interface.

We should resolve whether this is a change we want to make before 1.0.0.  If we wait till afterwards we won't be able to change ResMeta without breaking changes with custom handler returns, and we won't be able to change CallResMeta in case we break custom outbounds.

**Comment by breerly** [comment]
I predict that we will actually be marking specific interfaces as public. Outside of that, we will be free to add additional methods to interfaces in certain circumstances. To me, this seems like one of those.

Seems like we don't have to spend time on this pre-1.0 if that's the case.

**Comment by breerly** [comment]
Invalid because of #656
