### ISSUE TITLE
NewDispatcher should return a concrete type

### ISSUE THREAD

**Issue by bombela** [yarpc/yarpc-go#537]
Right now, `NewDispatcher()` returns a value type behind the interface `Dispatcher`. We should instead return a pointer to a concrete type. This type can implement multiple interfaces of course.

 - This is more in line with the Go style anyway.
 - We can have private methods for our internal use, for example, debugging/introspection requires some methods available on the dispatcher to return information.
 - We can add private methods for testing specific API before stabilization.

**Comment by kriskowal** [comment]
Fixed by #552
