### ISSUE TITLE
Move transport.Ack up

### ISSUE THREAD

**Issue by breerly** [yarpc/yarpc-go#556]
This is a main shape used by service authors in their oneway handlers, let's move it to `yarpc.Ack`.

**Comment by willhug** [comment]
with the api rewrite this is in /api/transport/ack is that reasonable?

**Comment by willhug** [comment]
wait, right, used by caller/callees, I got this.

**Comment by willhug** [comment]
hmmmmmmmmmmmmmmmmmmmmmmmmm
so since the dispatcher imports the /transport/ api, and transport uses the ack object we won't be able to move it to yarpc.Ack

We caaaaaan create an external version of the yarpc.Ack (similar to the external versions of Req/Res)

**Comment by willhug** [comment]
Also the dispatcher level does not use the ack object, it only gets returned based on the encoding/transport.
