### ISSUE TITLE
Don't recover from panics in Handlers?

### ISSUE THREAD

**Issue by akshayjshah** [yarpc/yarpc-go#557]
Proposal:

`panic`s aren't exceptions, and shouldn't be automagically `recover`ed - they're fatal errors, and the process should crash with a stack trace. In particular, I'm wary of introducing this behavior in frameworks.

I'd much prefer to return a 500-like status code if we get an unexpected error return value, leaving panics to crash the process.

**Comment by breerly** [comment]
@prashantv @billf could you weigh in here?

**Comment by breerly** [comment]
cc @yarpc/yarpc

**Comment by prashantv** [comment]
While panics should normally cause the process to crash, we also have to take consistency into account.

The standard library's HTTP handler will automatically `recover` if we don't:
https://play.golang.org/p/-jPgpnJMSM

So if we don't `recover` consistently in YARPC, TChannel and HTTP will have inconsistent behaviour based on transport, which I think is worse of an experience.

**Comment by akshayjshah** [comment]
Gross. I suppose if the standard library does it, we should too.

**Comment by breerly** [comment]
Is it better to turn off the auto-recover in HTTP?

**Comment by billf** [comment]
+1 to matching the standard library for consistent experience
