### ISSUE TITLE
StartStoppable docs are outdated

### ISSUE THREAD

**Issue by abhinav** [yarpc/yarpc-go#567]
// Starts the RPC allowing it to accept and process new incoming
    // requests.
    //
    // Blocks until the RPC is ready to start accepting new requests.
    Start() error

    // Stops the RPC. No new requests will be accepted.
    //
    // Blocks until the RPC has stopped.
    Stop() error

**Comment by breerly** [comment]
Looks fine to me (p.s. it's now called `yarpc.api.transport.Lifecycle`)
