### ISSUE TITLE
Peer.Start/StopRequest(dontNotify Subscriber) API unclear

### ISSUE THREAD

**Issue by abhinav** [yarpc/yarpc-go#571]
What exactly is the meaning of `dontNotify` here and why do we need this argument? If it means "don't notify this subscriber", that just feels like an API smell.

**Comment by kriskowal** [comment]
Will and I agree that this is smelly. The advantage is that it breaks a lock retention cycle during peer selection and allows us to proactively update the peer and peer list when we select a peer, while blocking.
