### ISSUE TITLE
Make CreateOpenTracingSpan/ExtractOpenTracingSpan private to hide our shame

### ISSUE THREAD

**Issue by abhinav** [yarpc/yarpc-go#572]
These functions accept a large number of arguments and the start time of the
request. This is just a weird thing to be passing around in a public API.

![image](https://cloud.githubusercontent.com/assets/41730/21154903/efd51ee4-c124-11e6-876e-a9c2c5efb24f.png)
![image](https://cloud.githubusercontent.com/assets/41730/21154910/f4d62ad2-c124-11e6-905d-66601cb2f2e3.png)

Why do we need the start time? Can we remove it and get similar information
from the `Context.Deadline`? If we can't remove the start time as an argument
and we can't find a cleaner API for this, I would rather we simply make this
internal.

**Comment by kriskowal** [comment]
Let’s make it private, even if it means duplication, and pay it off after 1.0.

**Comment by AlexAPB** [comment]
This should be public so that transports not implemented within yarpc-go can use this...but I agree it's clunky

what if we made this function part of the request object to reduce the number of arguments passed?

```
req.ExtractOpenTracingSpan(ctx,..)
```

**Comment by abhinav** [comment]
> ```
> req.ExtractOpenTracingSpan(ctx,..)
> ```

I would advise against that. IMO that's not a good enough reason to add the
method.
