### ISSUE TITLE
Basic logging

### ISSUE THREAD

**Issue by breerly** [yarpc/yarpc-go#574]
Currently servers with just an HTTP transport are silent when starting and sending/receiving requests. Perhaps we should take this as an opportunity to plumb a logger through and log some basic things.

**Comment by kriskowal** [comment]
We can punt this to post 1.0.0 since we can add a logger option to transport constructors without breaking backward compatibility.

**Comment by peter-edge** [comment]
Just noting this:

Please please let's not have a situation where people are locked into a specific logging library :) back in the day I wrote https://github.com/grpc/grpc-go/tree/master/grpclog to get rid of the dependency on glog, which has hard requirements for where it outputs logs. People have completely different ways of logging, and if this were to be locked into zap for example, yarpc may get less adoption.

Shameless plug: I haven't updated it in a long time, but [go.pedge.io/dlog](https://go.pedge.io/dlog).

**Comment by akshayjshah** [comment]
Closing this in favor of #894 and T841919.
