### ISSUE TITLE
Support Fallback Handler

### ISSUE THREAD

**Issue by kriskowal** [yarpc/yarpc-go#581]
Multiple customer use cases can be solved with the concept of a fallback handler, for the cases that a registry does not contain a procedure for an inbound request.

1. a proxy that gradually implements the procedures of the service it replaces.
2. a proxy that supports debug procedures, and forwards all else based on other request criteria.

The yarpc.Dispatcher Config could accept a fallback handler, as a catch-all for all requests that the registry does not match.

**Comment by abhinav** [comment]
Rather than explicitly only supporting the fallback case, what about a
`Registry` middleware interface accepted by `yarpc.Config`?

```go
package middleware

type Registry {
    ServiceProcedures(transport.Registry) []transport.ServiceProcedure
    Choose(context.Context, *transport.Request, transport.Registry) (HandlerSpec, error)
}
```

Fallback is then,

```go
func (fallbackRegistry) ServiceProcedures(r transport.Registry) .. {
    return r.ServiceProcedures()
}

func (fr fallbackRegistry) Choose(...) .. {
    spec, err := r.Choose(...)
    if err != nil {
        return fr.FallbackHandlerSpec
    }
    return spec, nil
}
```

**Comment by kriskowal** [comment]
YARPC now supports Router middleware that addresses this problem partially.

We also need to be able to detect unrecognized procedure errors from the map router. https://github.com/yarpc/yarpc-go/issues/931

Otherwise, this issue has been addressed.
