### ISSUE TITLE
ThriftRW Plugin: Lower case argument names in generated interfaces

### ISSUE THREAD

**Issue by abhinav** [yarpc/yarpc-go#590]
Server and client interfaces use upper cased parameter names for service methods.

https://github.com/yarpc/yarpc-go/blob/fdbad937b763e420178cde657f4de8b1dffaf115/internal/examples/thrift-keyvalue/keyvalue/kv/keyvalueserver/server.go#L43-L44

These should be lower cased or the name from the Thrift file should be used.

**Comment by kriskowal** [comment]
This issue has gone stale and I expect we can’t do anything about it post-1.0. Please advise/close.

**Comment by abhinav** [comment]
We can do this post-1.0. It's just parameter names in the generated interfaces. That's actually why we pushed it to post-1.0 rather than doing it earlier.

**Comment by abhinav** [comment]
Still an issue

**Comment by peter-edge** [comment]
Are we ever going to fix this? I think we might want to just mark as "wontfix" because the effort here is decent (I remember looking into it) without much upside.

**Comment by abhinav** [comment]
Closing as wontfix. This doesn't have any behavioral consequences. We can
revive this if someone has time to work on it.
