### ISSUE TITLE
Improvements for implementing encodings outside YARPC

### ISSUE THREAD

**Issue by abhinav** [yarpc/yarpc-go#596]
You can currently implement a YARPC-compatible encoding outside the YARPC repo
but the following issues hurt usability:

- [ ] Server: `request.Encoding` must be matched against the encoding name
      manually
- [ ] Server: Request body decode error message has to be written by hand:

	    transport.BadRequestError(fmt.Errorf("failed to decode [..]", ..))
- [x] ~~Server: Users have to implement their own `yarpc.ReqMeta` given a
      `transport.Request`~~   
    - No longer an issue. Resolved by InboundCall and OutboundCall APIs.
- [x] ~~Client: Users have to implement their own `yarpc.CallResMeta` given a
      `transport.Response`~~
    - No longer an issue. Resolved by InboundCall and OutboundCall APIs.

#593 demonstrates how the raw encoding would look if it was implemented
outside the YARPC library.

**Comment by peter-edge** [comment]
@abhinav is this still an issue?

**Comment by abhinav** [comment]
These improvements made sense when we were more stringent about error messages. We can punt this until someone asks for it.
