### ISSUE TITLE
Rename registry, registrar, registrant

### ISSUE THREAD

**Issue by breerly** [yarpc/yarpc-go#605]
This clears up the concept of routing. cc @AllenLuUber 
```
registry --------> router

registrar--------> routeTable

registrant-------> procedure
```

> A router contains many procedures in order to route requests, we provide a MapRouter, and a custom router can be provided when a dispatcher is instantiated

**Comment by abhinav** [comment]
Actually we do need a separate query-only thing for routers to be used from routing-time middleware.

**Comment by breerly** [comment]
Ok, maybe `RouteTable`?
