### ISSUE TITLE
Codegen test

### ISSUE THREAD

**Issue by breerly** [yarpc/yarpc-go#606]
Write a test that actually runs codegen and verifies the out.

**Comment by kriskowal** [comment]
This will be complicated since running go generate blindly corrupts one of the files under encoding/. We will need to fix or work around. I’m moving this to the post-1.0.0 triage milestone since it does not block a release.

**Comment by abhinav** [comment]
encoding/ issue fixed in https://github.com/yarpc/yarpc-go/pull/621

**Comment by abhinav** [comment]
We now have tests for the ThriftRW plugin.
