### ISSUE TITLE
Consider moving api/* to api/x/*

### ISSUE THREAD

**Issue by breerly** [yarpc/yarpc-go#610]
@willhug brought up an interesting idea - now that we've created the `api/` package, why not move `api/*` to `api/x/*`.

In practice, this would mean that for 1.0.0 we would be committed to the APIs that Service Authors use, but would still be able to break contributor APIs like transports, encodings, middleware, and peers.

This is a pretty big hammer, so let's discuss the pros/cons.

**Comment by kriskowal** [comment]
There isn’t a practical way to get back down from api/x/* to api/* post 1.0.

**Comment by breerly** [comment]
Yeah, and I think that would also mean that we would have to make all the concrete impls x/ as well, which doesn't seem practical.

**Comment by kriskowal** [comment]
Recommend close.

**Comment by breerly** [comment]
Agreed here
