### ISSUE TITLE
Rename InboundMiddleware to HandlerMiddleware

### ISSUE THREAD

**Issue by bombela** [yarpc/yarpc-go#622]
before it is too late.

Outbound midleware works at the outbound level. You wrap an existing outbound with a given outbound middleware and you get a new Outbound.

Inbound middleware works at the handler level. You wrap an existing handler with a given inbound middleware and you get a new handler.

See the problem? Renaming to Handler reads way better:

Handler middleware works at the handler level. You wrap an existing handler with a given handler middleware and you get a new handler.

(btw, I am the one who fucked up the naming).

**Comment by abhinav** [comment]
Handler is a fairly overloaded term. For example "Handler error" makes less
sense to users than "Inbound error". Calling it HandlerMiddleware might be
confusing. I don't feel strongly about it, though.

Thoughts @yarpc/golang?

**Comment by breerly** [comment]
I don't buy that - I think that we should lean in and use inbound/outbound terminology more - it's a nice mental model for customers.

**Comment by bombela** [comment]
handler/outbound is inherently asymmetric, and inbound/outbound hides it. Up to you guys. I was having trouble mapping some mental model during my work on introspection, and I realized the word inbound instead of handler confused the heck out of me. Of course, our users should have the easier path.

**Comment by breerly** [comment]
I think the current term is probably ok to 1.0 with - if users find that confusing, we can add this to a 2.0 wishlist.
