### ISSUE TITLE
Lifecycle Start/Stop is not fully thread-safe

### ISSUE THREAD

**Issue by bombela** [yarpc/yarpc-go#634]
The current implementation of Lifecycle doesn't protect from calling Start/Stop in the wrong order. You can call Stop() then Start() now, calling Stop() again will be a noop, and nothing will be ever stopped.

Additionally, the IsRunning() function (as documented in the Lifecycle interface) cannot return a consistant result as it is not atomic.

We should instead implement this Lifecycle as as single atomic with few possibles values, in order:
 - IDLE
 - STARTING
 - RUNNING
 - STOPPING
 - STOPPED

You can always move forward to the next value in the order above.
 - IDLE is the starting state
 - STOPPED is the final STATE.
 - There is no possibility to move backward.

In more details:
 - Start() can only move from IDLE to RUNNING. The STARTING state is used during the execution of the Start function. This prevents calling Stop() on a partially Started object.
- Stop() can only move from RUNNING to STOPPED. Of course as we can never leave the STOPPED state, the intermediate STOPPING state is only there to keep symmetry with the STARTING state. This might also be useful for debugging: why is my state stuck in STOPPING for 15min for example.
 - IsRunning() returns STARTING || RUNNING || STOPPING (including STOPPING is debatable).
 - LifeCycleState() could return the full state as an enum, for you know whatever reason.

**Comment by willhug** [comment]
Yeah, there is a race condition there.  Luckily most of this logic is located in the lifecycleOnce code, so we can implement the understanding of these state changes under the hood without changing the api (except for returning the full state)

I can take this on

**Comment by abhinav** [comment]
Resolved by #642
