### ISSUE TITLE
Symlinks messing with import paths

### ISSUE THREAD

**Issue by peter-edge** [yarpc/yarpc-go#659]
Why did this go in? https://github.com/yarpc/yarpc-go/commit/a9a4381838ceb20e315c7b71b04b52a30dd48e10

This might make it easy to find these things, but it messes with the import paths - all the import paths in the code are still `go.uber.org/yarpc/internal/{crossdock,examples}`, but this makes it seem like they should be `go.uber.org/yarpc/{crossdock,examples}`, and I bet some tools will get messed up because of this. Even if they don't, it's confusing when I want to import something and I see gocode in the symlink directories (but might not notice they are symlinks), and then do the wrong import.

**Comment by breerly** [comment]
Fair, we can remove them and then link from the README instead.
