### ISSUE TITLE
tchannel NewTransport should return errors right away

### ISSUE THREAD

**Issue by bombela** [yarpc/yarpc-go#675]
Take a look at https://github.com/yarpc/yarpc-go/blob/8a2ae3161b5efd6e07d38273f00a152821cec147/transport/tchannel/channel_transport.go#L39

This function stores the `error`, and returns it when Start() is called. That's probably not something we should do?

**Comment by abhinav** [comment]
I think the original intention was to be able to easily build transports but I
don't see why that's useful. Sure, feel free to make `NewChannelTransport`
return an error. Now's the time to change this.

**Comment by breerly** [comment]
I'm onboard.

**Comment by abhinav** [comment]
Resolved by #678
