### ISSUE TITLE
http NewOutbound is missing http Outbound options 

### ISSUE THREAD

**Issue by bombela** [yarpc/yarpc-go#679]
func (t *Transport) NewOutbound(chooser peer.Chooser) should be taking outbound options similar to NewSingleOutbound.

**Comment by breerly** [comment]
@bombela wow, great catch!

**Comment by abhinav** [comment]
Fixed yesterday https://github.com/yarpc/yarpc-go/blob/dev/transport/http/outbound.go#L76
