### ISSUE TITLE
Consider using go:generate again

### ISSUE THREAD

**Issue by abhinav** [yarpc/yarpc-go#692]
The generate.sh script originally sounded nicer and it's faster to regenerate
everything with it but it makes regenerating a subset of the code impossible.
If I'm iterating on a specific package, regenerating everything with `make
generate` takes a lot longer than a package-local `go generate`.

Let's not revert the change though. We all agree that our `go:generate` was
out of hand before. 

If we agree that we should use `go:generate` again, we should start
adding/moving `go:generate` clauses as we touch that code. But let's avoid,

-   Adding updateLicenses to `go:generate` clauses. That can run once at the
    top-level when we call `make generate`.
-   Adding five different commands to generate a single file/piece of code. At
    that point, a standalone script (in the scripts/ directory) or a local
    Makefile is probably preferable.

Thoughts? CC @yarpc/golang @peter-edge

**Comment by peter-edge** [comment]
It only takes 8 seconds on my machine to run it:

```
$ PATH=/Users/peteredge/gocode/src/go.uber.org/yarpc/.tmp:$PATH time ./scripts/generate.sh
        8.00 real         6.97 user         2.23 sys
```

Is that too much?

**Comment by peter-edge** [comment]
Even if it is, note that basically every command can be parallelized, which I would prefer to do instead

**Comment by prashantv** [comment]
I'd vote for Makefile which supports real inputs and outputs, and can be parallelized.

**Comment by abhinav** [comment]
IMO 8 seconds is really long if the corresponding command when run manually is
instant. I was making a few changes to the ThriftRW plugin and having to
regenerate everything instead of the specific package being tested feels like
an eternity.

Parallelizing commands (in a Makefile or otherwise) sounds reasonable to me if
that brings the time down. I can look into porting the rules into a Makefile
when I get a chance.

**Comment by peter-edge** [comment]
Note the actual time (~22s) is mostly because of the rebuilding of the go binaries in the Makefile, which was true before the PR that added scripts/generate.sh (and a lot of that is our favorite, glide), although I wanted this logic to be simplified too optimally.

**Comment by abhinav** [comment]
Let's revisit this if it becomes a problem again.
