### ISSUE TITLE
Turn on Java in Crossdock tests

### ISSUE THREAD

**Issue by willhug** [yarpc/yarpc-go#704]
https://github.com/yarpc/yarpc-go/pull/703 turned off Java in crossdock tests so they would pass in yarpc-go again, this is the task to add java back to the crossdock tests after yarpc-java calms down again.

**Comment by vivekrsharma** [comment]
This is WIP. Java doesn't support tchannel transport anymore. There is  an active PR https://github.com/yarpc/yarpc-go/pull/849 . This also needs some changes in crossdock to support prunning of axis https://github.com/crossdock/crossdock/issues/82
