### ISSUE TITLE
Rework yarpc.Outbounds

### ISSUE THREAD

**Issue by willhug** [yarpc/yarpc-go#706]
Currently, users create a set of outbounds where the key is the service name, and the value is the outbound. This is a bit confusing since `transport.Outbounds` is not actually a collection of outbounds, it contains a single possible outbound for each RPC Type (unary, oneway, etc):

```
type Outbounds map[string]transport.Outbounds
```

Instead, we should make it more obvious that the key is just the outbound key, and that the value is not a set of outbounds, but an `OutboundSpec`:

```
type Outbounds map[string]transport.OutboundSpec
```

This is a breaking change, so adding to 2.0 Wishlist.

**Comment by breerly** [comment]
@abhinav let's chat about incorporating this into yarpc-java for 1.0
