### ISSUE TITLE
Introspection: Outbound <-> peer chooser <-> peer provider

### ISSUE THREAD

**Issue by bombela** [yarpc/yarpc-go#723]
The peer provider... provides peers. The peer chooser implements an algorithm to choose peers from a given peer provider given some constraint (least loaded, least recently used, simple round robin...). Finally the outbound asks the peer chooser what peer should it uses every-time a new RPC message has to be sent.

Many outbounds can share a peer chooser. And many peer choosers can share a single peer provider.

We need the introspection mechanism to expose this information and for the debug pages to display them.

**Comment by kriskowal** [comment]
Notably, the peer chooser *does not need* to have a forward reference to the peer provider. The peer provider has a reference back to the peer subscriber (peer list / peer chooser) and sends Update(add, remove) messages.

Our current compromise for lifecycle management is that we create a peer chooser that captures both the peer list and peer provider, so it can start and stop both.
