### ISSUE TITLE
Upgrade jaeger-client-go to ^2.0

### ISSUE THREAD

**Issue by sectioneight** [yarpc/yarpc-go#732]
It was released a few days ago, and we'd like to use it, but can't currently do to the ^1 constraint in YARPC.

**Comment by breerly** [comment]
Looks like an awesome release. We'll need a PR that updates to the latest APIs.

@yurishkuro do you have cycles over there to get us a PR? We are jam packed at the moment.

**Comment by sectioneight** [comment]
How big is the API change? Is it something I could spike out this weekend being totally unfamiliar with either of these codebases?

**Comment by yurishkuro** [comment]
The API changes are around initialization (using functional options instead of passing struct) and the metrics API. If you are not in a hurry, @black-adder can do a PR on Monday.

**Comment by sectioneight** [comment]
Monday seems fine. We'd like to launch UberFx (20 Feb) beta with jaeger-client-go 2

**Comment by sectioneight** [comment]
@black-adder is this on your plate today?

**Comment by breerly** [comment]
Resolved by https://github.com/yarpc/yarpc-go/pull/735

**Comment by sectioneight** [comment]
Thanks!

**Comment by madhuravi** [comment]
When can we expect a release with this change? @abhinav

**Comment by bombela** [comment]
https://github.com/yarpc/yarpc-go/releases/tag/v1.4.0 released
