### ISSUE TITLE
hide panic detail to caller

### ISSUE THREAD

**Issue by yutongp** [yarpc/yarpc-go#734]
right now when inbound handler panic, it does this:
https://github.com/yarpc/yarpc-go/blob/61fa69b4a04faa5d1dc57b5a2ce44f93c16e6485/api/transport/handler.go#L102
```
	defer func() {
		if r := recover(); r != nil {
			log.Printf("Unary handler panicked: %v\n%s", r, debug.Stack())
			err = fmt.Errorf("panic: %v", r)
		}
	}()
```

I feel like `r` should not be as part of err message and send back to caller. It may expose too much server detail if we consider the error message may send back to the mobile client through a proxy.

maybe just some general message like: "server panic"

**Comment by peter-edge** [comment]
@yutongp is this still an issue/is it ok if we close this?

**Comment by peter-edge** [comment]
@breerly any thoughts? @kriskowal @willhug?

**Comment by peter-edge** [comment]
Closing this as there seems to be no further interest in pursuing it.
