### ISSUE TITLE
Proposal for Thrift envelope compatibility with yab

### ISSUE THREAD

**Issue by prashantv** [yarpc/yarpc-go#741]
Thrift envelopes are in an inconsistent state across our tools:
 - `yab` defaults to envelope on for HTTP (b/c with Apache Thrift HTTP servers), but disables enveloping for TChannel.
 - `yarpc-go` 1.* defaults to envelope off (consistently across transports), but allows users to opt in to enable enveloping on the server side and client side.

A request does not currently include any metadata about whether it's enveloped or not, which means that the client/server must be configured the same, or the user will get serialization errors.

To improve UX with regards to envelope, I think we should add a new header, `RPC-Thrift-Envelope` which specifies whether the request is enveloped or not. `yarpc-go` thrift services would handle both enveloped and unenveloped requests based on the value of this header. Since we're post-1.0, if the header is missing, we fallback to the current behaviour.

Clients (both `yab` and `yarpc-go` clients) should set the `RPC-Thrift-Envelope` header when for Thrift requests so the server can handle the request correctly.

This will be a backwards compatible change to YARPC so we can release this as a minor.

cc @breerly @abhinav

**Comment by breerly** [comment]
I'm onboard - this sounds sensible and doesn't break any existing APIs or customers.

**Comment by Willyham** [comment]
I feel like this is crucial to enable realistic external adoption of this library.

**Comment by kriskowal** [comment]
We could alternately vary the Rpc-Encoding header e.g., "thrift" ("tbinary"), "tbinary-enveloped", "tcompact", "tcompact-enveloped".

**Comment by prashantv** [comment]
I think having a custom`RPC-Encoding` would be the ideal solution, but it's not 100% backwards compatible (see https://github.com/yarpc/yarpc-go/pull/1097#issuecomment-307461666).

**Comment by peter-edge** [comment]
Tracked internally.
