### ISSUE TITLE
Get rid of transport.Procedure{ Service }

### ISSUE THREAD

**Issue by bombela** [yarpc/yarpc-go#742]
```go
type Procedure struct {
	// Name of the procedure.
	Name string

	// Service or empty to use the default service name.
	Service string // <<<<<<<----- we should get rid of this

	// HandlerSpec specifiying which handler and rpc type.
	HandlerSpec HandlerSpec

	// Encoding of the handler, for introspection.
	Encoding Encoding

	// Signature of the handler, for introspection. This should be a snippet of
	// Go code representing the function definition.
	Signature string
}
```

The `Service` string in the Procedure struct can only make sense in a peer to peer request. This is because on the wire, a procedure is a tuple (DispatcherService, ProcedureName) and not, for example (DispatcherService, ProcedureService, ProcedureName).

In a peer to peer connection, you effectively get 3 information: (endpoint, Service, ProcedureName). The endpoint will act as the DispatcherService routing, and the Service will match the Service in the Procedure struct above.

But as soon as you proxify (during distributed routing for example), the endpoint is fixed to the proxy service. This leaves (Service, ProcedureName). Of course the proxy uses the Service to determine which process should receive the request and this leaves Procedure the only variable at the destination.

If ones want to namespace, it is easy to prefix the ProcedureName with a common string:
 - MyService/Get
 - MyService/Set
 - MyService/AutoDestruct

This makes the Service string in the transport.Procedure struct not only useless in most cases, but also really confusing.

#### Path forward

When the Service in transport.Procedure is left to "", yarpc will set the Service to the Dispatcher Service.
We also note that all convenience functions for building transport.Procedure(s) never set the Service in transport.Procedure. This means we can probably deprecate this attribute, and remove the burden of trying to handle multiple "ProcedureService" in the Routing table.

**Comment by breerly** [comment]
@bombela thanks for creating this.

@abhinav  @bpon @vivekrsharma if it's possible to avoid this weirdness in yarpc-java 1.x, that would be great.

**Comment by peter-edge** [comment]
@breerly is this still active?

**Comment by breerly** [comment]
We'll want this on the 2.0 wishlist task, if you're looking to consolidate.
