### ISSUE TITLE
Expose information about the remote peer on the Call object

### ISSUE THREAD

**Issue by prashantv** [yarpc/yarpc-go#753]
For debugging purposes, it can be useful to have some information about the remote peer.

Suggest adding an interface `RemotePeer` that should have at least some string identifier for the peer:
```go
type RemotePeer interface {
  Identifier() String
}
```

Transports could add more information, so the TChannel transport might have a peer interface with more information.

This remote peer should be exposed on the `yarpc.Call` object.

Thoughts @abhinav @breerly 

cc @arturaslap

**Comment by breerly** [comment]
I could get behind this for sure!

**Comment by kriskowal** [comment]
We can reuse the peer identifier interface, same as described. These are intended to cast to a given concrete type per transport.

**Comment by peter-edge** [comment]
@kriskowal @prashantv is this still an issue?

**Comment by abhinav** [comment]
Yeah, this is still a valid issue. It's a reasonable feature request IMO.

**Comment by peter-edge** [comment]
Should we merge this with #810? @abhinav @prashantv

**Comment by abhinav** [comment]
Moved to internal ticket T1396795.
