### ISSUE TITLE
Clarify Naming of Oneway/Unary

### ISSUE THREAD

**Issue by willhug** [yarpc/yarpc-go#762]
Users have brought up that they are confused by these terms and they don't connect which RPC messaging patterns they are used to.

**Comment by breerly** [comment]
Can you be more specific here? 

I suggest describing the problem and then suggesting a possible solution.

For example, what exactly is confusing about the naming or Oneway/Unary?

**Comment by breerly** [comment]
Or does this simply mean "people are confused by these terms and they don't connect which RPC messaging patterns they relate to"...?

**Comment by willhug** [comment]
updated comment with your second point :)
