### ISSUE TITLE
Use quay.io instead of Docker Hub for images

### ISSUE THREAD

**Issue by peter-edge** [yarpc/yarpc-go#781]
I've used quay.io instead of Docker Hub for hosting Docker images for a while, and long story short, I have found it to be a lot nicer, faster, more reliable, etc. Making this change is trivial, we just need an Uber quay.io account, and then you update `docker {push,pull} uber/foo` to `docker {push/pull} quay.io/uber/foo`. Could we do this?

**Comment by abhinav** [comment]
We haven't experienced any problems with DockerHub so I'm not sure about the switch. We use it exclusively for cross-language tests, not to serve the project so it doesn't really affect user experience. Also, does it require extra configuration to switch to quay? I would prefer it if it Just Worked without much setup, which we already get with DockerHub.

**Comment by peter-edge** [comment]
Yep, it's the exact same (same commands, etc) just you use a quay.io/
prefix for docker image names. We just need to setup a quay.io account,
 the actual service is faster than docker hub.

**Comment by breerly** [comment]
With Abg here,

Docker Hub has been completely fine, so I don't see investing here
producing much value.

Since we only use Docker Hub to publish Crossdock images, the only thing
that we really care about is availability, which Docker Hub has been good
about.

G
