### ISSUE TITLE
thriftrw-plugin-yarpc should probably be named thriftrw-plugin-yarpc-go

### ISSUE THREAD

**Issue by peter-edge** [yarpc/yarpc-go#782]
The call right now to use the yarpc go plugin is `thriftrw --plugin=yarpc`. This should probably be `thriftrw --plugin=yarpc-go` - the output of `thriftrw-plugin-yarpc` is golang specific stubs, so when we talk about java etc, there should be a differentiation (there's technically nothing preventing thriftrw-go from generating java stubs).

A problem here is that this is a breaking change for users.

**Comment by breerly** [comment]
Let's add this to the 2.0 wishlist tag - we can't make any breaking changes until then.

**Comment by peter-edge** [comment]
Already done heh
