### ISSUE TITLE
Making a call when a dispatcher has not started should result in an error

### ISSUE THREAD

**Issue by prashantv** [yarpc/yarpc-go#786]
Currently, users get a context deadline exceeded/timeout, but ideally we would return a more user friendly error.

**Comment by peter-edge** [comment]
@kriskowal @prashantv is this still an issue?

**Comment by kriskowal** [comment]
@peter-edge Yes. We could replace the deadline errors with YARPC errors.

**Comment by andymaule** [comment]
+1 to fixing this. I just hit this, and the misleading error message took a long time to figure out. Other people seem to have hit this too, judging by some questions on stackoverflow.
