### ISSUE TITLE
Distinguish PII in headers

### ISSUE THREAD

**Issue by akshayjshah** [yarpc/yarpc-go#788]
We should have a mechanism to distinguish PII-containing headers and baggage from metadata that's safe to log; otherwise, it's not safe to ever log this information.

**Comment by kriskowal** [comment]
- carrying PII annotations over the wire is not feasible. We could only annotate the key or the value, and there are existing PII bearing headers and baggage.
- a black list provides a weak assurance that PII isn’t logged.
- a white list provides a stronger assurance.

A black list or white list can be implemented without involving changes to the RPC library. We can mark PII in IDL and communicate that with go tags, but that doesn’t cover headers or baggage.

**Comment by akshayjshah** [comment]
I don't see this as needing an ironclad solution right away; I'm in favor of starting with a simple name convention (e.g., PII-containing header/baggage keys contain `-PII`). If we have existing PII in headers/baggage, they're *definitely* being logged all over the place, so introducing a sane convention won't make things any worse. (Maybe?)

Annotations for PII in bodies makes sense, though.

**Comment by peter-edge** [comment]
Do we still want to track this? We could come up with a solution, but we have to figure out how to define it in a transport-agnostic way.

**Comment by akshayjshah** [comment]
There's already a transport-agnostic representation of headers.

**Comment by peter-edge** [comment]
Tracked internally.
