### ISSUE TITLE
leastpending: exclude unconnected peers from available peer pool

### ISSUE THREAD

**Issue by kriskowal** [yarpc/yarpc-go#792]
The least pending peer chooser has a bug where it will treat unconnected peers as available. The symptom is that these peers produce connection errors. A request should fail with a connection error only in the rare case that a peer becomes fully disconnected in the narrow interval after being chosen.

**Comment by peter-edge** [comment]
@kriskowal is this still an issue?

**Comment by peter-edge** [comment]
@kriskowal this one too :-)

**Comment by kriskowal** [comment]
Fixed this last week with `peer/pendingheap`. We can deprecate `x/peer/peerheap`.
