### ISSUE TITLE
Writing transports outside YARPC

### ISSUE THREAD

**Issue by abhinav** [yarpc/yarpc-go#829]
Although it's possible to write transports outside YARPC, it's not quite
possible to write well-behaved transports where well-behaved is defined as
having integration with YARPC error handling.

That's because all our transports rely on internal error constructors.

```
 $ rg internal/errors transport/*
transport/roundtrip_test.go
35:     "go.uber.org/yarpc/internal/errors"

transport/tchannel/channel_outbound.go
29:     "go.uber.org/yarpc/internal/errors"

transport/tchannel/handler.go
30:     "go.uber.org/yarpc/internal/errors"

transport/http/inbound.go
28:     "go.uber.org/yarpc/internal/errors"

transport/http/handler.go
30:     "go.uber.org/yarpc/internal/errors"

transport/http/ttl.go
30:     "go.uber.org/yarpc/internal/errors"

transport/http/outbound.go
35:     "go.uber.org/yarpc/internal/errors"

transport/x/cherami/inbound.go
29:     "go.uber.org/yarpc/internal/errors"

transport/x/redis/inbound.go
29:     "go.uber.org/yarpc/internal/errors"
```

It's impossible to construct correct error types as a transport author without
relying on these constructors. We should expose appropriate constructors to
make this possible.

Branch [transport-errors][1] (#607) has some preliminary work on this but it's
been stalled for a while.

[1]: https://github.com/yarpc/yarpc-go/tree/transport-errors

**Comment by peter-edge** [comment]
We also generally rely on `internal/sync` for `LifecycleOnce`.

**Comment by kriskowal** [comment]
Although anyone can implement Lifecycle, LifecycleOnce does make it a lot easier to get right. It is also generally useful beyond YARPC. We should perhaps produce a lifecycle package. In the interim, perhaps we should move "./internal/sync".LifecycleOnce/Once to "./lifecycle".Once/NewOnce. This will also make it easier to import—sync as intsync is a pain point internally.

**Comment by peter-edge** [comment]
Do we want to keep on tracking this here?
