### ISSUE TITLE
Do we *really* have to use cram?

### ISSUE THREAD

**Issue by peter-edge** [yarpc/yarpc-go#855]
I get that it seems like a cool tool? But

- Not everyone knows it - when it comes to the build system, I'd prefer if it was limited to shell + go commands. This makes it so much simpler and easier for new people to come in (for example, I have no idea about this cram thing)
- We have additional dependencies, ie virtualenv and then cram. It's annoying.
- We can do the input/output testing just using `diff`, i.e. similar to what I'm doing for the protobuf example

**Comment by breerly** [comment]
I don't think we feel strongly - if you can replace its functionality and leave us with some lighter then I'm sure we'd be onboard.
