### ISSUE TITLE
TChannel Transport ownership

### ISSUE THREAD

**Issue by abhinav** [yarpc/yarpc-go#87]
Right now, the user has to construct the `tchannel.Channel` manually and thread it down to the inbound and outbound transports. There's some duplication of information there too (the caller name). It would be nice if we could provide an API that would take care of constructing the Channel for the user and making the TChannel inbound and outbounds share it. It would need to pick up the service name from the channel.

**Comment by breerly** [comment]
+1

**Comment by abhinav** [comment]
ChannelTransport addresses this
