### ISSUE TITLE
Establish convention for mapping gRPC path (/interface/method) to procedure

### ISSUE THREAD

**Issue by kriskowal** [yarpc/yarpc-go#908]
gRPC paths take the form `/interface/method`. Thrift maps cleanly, from `Interface::method`. For gRPC with Protobuf, the YARPC procedure is never reified, but could be the same as Thrift. For other encodings, the procedure name has a freer form. I propose that the we should lift the "interface" name from the dispatcher and use the whole procedure for the method.

So if you have a dispatcher named my-service, and a raw or JSON procedure named `echo/echo`, the corresponding gRPC path would be `/my-service/echo%2Fecho`, using encodeURIComponent to capture the method.

Perhaps we can distinguish these cases by adding `Interface string` to `transport.Request`.

Regardless, we need a convention to solve the problem that gRPC needs two properties where YARPC only has `transport.Request.Procedure`. I favor reusing the service name over e.g., `__default__/echo__echo` or `echo__echo/__default`.

**Comment by peter-edge** [comment]
Hmm I'm not sure about this, let's discuss.
