### ISSUE TITLE
First class support for REST and gRPC forwarding

### ISSUE THREAD

**Issue by kriskowal** [yarpc/yarpc-go#910]
REST and gRPC both support proxy cases that can’t enter the transport.Request abstraction. For example, REST and gRPC both supply a path. The gRPC transport can’t accept requests for unrecognized procedures.

For both of these cases, we will need to support a fallback handler that can forward unrecognized requests, at least over the same transport, inbound to outbound, using a peer chooser. We may or may not be able to apply middleware to the fallback or shunt chain.

Forwarding non-YARPC-flavored requests using YARPC has now come up as a case for two customers in our own infrastructure.

cc @blampe

**Comment by peter-edge** [comment]
I think I could use some more clarification here - this may be a wider issue, not just gRPC specific, correct? I think the current API limits our ability a bit here, I may be wrong.

**Comment by kriskowal** [comment]
@peter-edge That is correct. This issue is scoped to both REST and gRPC.

**Comment by peter-edge** [comment]
Can we rename this issue to something else/should we track this here?
