### ISSUE TITLE
gRPC Allow overriding grpc encoding headers

### ISSUE THREAD

**Issue by willhug** [yarpc/yarpc-go#911]
Currently we're bound to a single encoding header in GRPC, we've hardcoded it to "proto" (so we're compatible with proto grpc services, but not any other type of encoding),  In order to be fully compatible with grpc, and to remove the differences between yarpc/grpc, yarpc should piggy-back/override on the grpc encoding header.

**Comment by kriskowal** [comment]
It may be possible to replace `Rpc-Encoding: ?` with `Content-Type: application/grpc+?` to flush with existing gRPC callers and services.

**Comment by peter-edge** [comment]
This potentially involves external work https://github.com/grpc/grpc-go/issues/803

**Comment by peter-edge** [comment]
This is being worked on separately, no need to track here.
