### ISSUE TITLE
gRPC add benchmarks

### ISSUE THREAD

**Issue by willhug** [yarpc/yarpc-go#912]
Some of the code in GRPC is heavy on allocating memory (for instance, on inbound calls we decode directly into a byte array which is likely heavy in allocations).

We should have a decent idea about how we benchmark for the GRPC transport.

TBH we should do this for all transports, gRPC gets the task because it's new and flashy XD

**Comment by peter-edge** [comment]
I think we should rename this to a tracking task for all benchmarks, as you said, it's not a gRPC issue, and this is a cleanup we need to institutionalize for the whole codebase - thoughts?

I don't think this should be on the tracking issue for gRPC, rather we need something of a "cleanup" label for yarpc-go as a whole, if that makes sense. @willhug
