### ISSUE TITLE
Use existing generated gRPC Client and Server interfaces for YARPC?

### ISSUE THREAD

**Issue by peter-edge** [yarpc/yarpc-go#920]
As an example, here's the generated grpc-go Client and Server interfaces:

```go
type KeyValueClient interface {
	GetValue(context.Context, *GetValueRequest, ...grpc.CallOption) (*GetValueResponse, error)
	SetValue(context.Context, *SetValueRequest, ...grpc.CallOption) (*SetValueResponse, error)
}

type KeyValueServer interface {
	GetValue(context.Context, *GetValueRequest) (*GetValueResponse, error)
	SetValue(context.Context, *SetValueRequest) (*SetValueResponse, error)
}
```

Here's the generated yarpc-go Client and Server interfaces:

```go
type KeyValueYarpcClient interface {
	GetValue(context.Context, *GetValueRequest, ...yarpc.CallOption) (*GetValueResponse, error)
	SetValue(context.Context, *SetValueRequest, ...yarpc.CallOption) (*SetValueResponse, error)
}

type KeyValueYarpcServer interface {
	GetValue(context.Context, *GetValueRequest) (*GetValueResponse, error)
	SetValue(context.Context, *SetValueRequest) (*SetValueResponse, error)
}
```

Note that the only difference is that the grpc-go Client interface takes a `grpc.CallOption` variadic argument, while the yarpc-go Client takes `yarpc.CallOption` variadic argument, while the Server interfaces are exactly the same.

We could easily use the same Server interface, which means that existing grpc-go server implementations will be plug-and-playable with yarpc-go, and in theory we could do the same with Clients, however the difference between `grpc.CallOption` and `yarpc.CallOption` is harder to reconcile. Note that when we go to streaming methods, this may be more difficult, but I think this might be worth discussion.

**Comment by kriskowal** [comment]
This is at the very least an interesting opportunity.
