### ISSUE TITLE
Naming of internal struct fields in gRPC

### ISSUE THREAD

**Issue by peter-edge** [yarpc/yarpc-go#922]
@kriskowal @willhug we're having some disagreement as to what we should name the various fields within the grpc package, we should discuss this and agree on one.

**Comment by kriskowal** [comment]
- FullMethod, I suggested Path, @willhug suggested grpcMethod
- ServiceName, I suggested InterfaceName to distinguish ServiceName for routing purposes
- fine with MethodName meaning gRPC method name, as distinguished from YARPC procedure name
