### ISSUE TITLE
Revise peer list lifecycle contract

### ISSUE THREAD

**Issue by kriskowal** [yarpc/yarpc-go#932]
The behavior currently:

- a peer list cannot be updated until it has started
- a peer list cannot be updated after it has stopped, because it automatically releases all retained peers
- a peer list cannot provide a peer when it is not running but blocks until it has started

Proposed contract:

- a peer list can be updated at any time
- updates must be serialized to ensure remove after add
- every remove for a corresponding previous add must be honored without an error, regardless of whether the peer list is running
- every invalid remove without a corresponding add must be an error, regardless of whether the peer list is running
- a peer list must not retain a peer until it has started
- a peer list must release all retained peers when it stops

This requires the peer list to track the set of known peers separately from retained peers. The peer list must retain all known peers when it starts, and release all known peers when it stops.

**Comment by peter-edge** [comment]
@kriskowal is this still valid?

**Comment by kriskowal** [comment]
This is fixed! As of last week, all our peer lists hold peer identifiers in reserve outside of lifecycle, and peers are only retained while running.

**Comment by kriskowal** [comment]
To clarify, @willhug fixed this for roundrobin a long while back. We just released the change that makes this default behavior for all peer lists past and future.
