### ISSUE TITLE
1st-class support for explicit client and server errors

### ISSUE THREAD

**Issue by breerly** [yarpc/yarpc-go#933]
In addition to our existing error handling, we need a 1st-class way for handlers to explicitly indicate that an error is an:

- client error - something on the caller-side went wrong
- server error - something on the server-side went wrong

This will let standardized metrics emit this crucial data, which will then be used by SRE.

## Proposal

We introduce a new 1st-class client and server error in YARPC, which can be explicitly used from handlers or middleware:

```golang
// explicitly setting server error
return nil, yarpc.NewServerError(err)

// explicitly setting client error
return nil, yarpc.NewClientError(err)
```

Additionally, the calling side and middleware can detect which type of error has occurred:

```golang
// detecting if err is server error
if yarpc.IsServerError(err) {}

// detecting if err is client error
if yarpc.IsClientError(err) {}
``` 

Finally, services using binary encodings like Thrift should be able to indicate which exceptions are of type client or server, allowing them to return a richer error with additional metadata.

```thrift
service Fortunes {
  // Create a new Fortune synchronously.
  CreateResponse create();
  // Fetch an already-created Fortune by UUID.
  GetResponse get(1:GetRequest request) throws (
    1:ClientError clientError ( type = "client" ), 
    2:ServerError serverError ( type = "server" ),
  );
}
```

Note that the introduction of this means that each transport needs to determine how to transmit this info, so that it can be picked up correctly on the client side or sniffed off the wire.

**Comment by kriskowal** [comment]
There is an overlapping concern that we need to be able to express common application error classes for gRPC, e.g., "not found" and "permission denied".

Related:

- https://github.com/yarpc/yarpc-go/issues/905
- https://github.com/yarpc/yarpc-go/issues/687#issuecomment-293428062
- https://github.com/yarpc/yarpc-go/issues/856

**Comment by akshayjshah** [comment]
Generally sounds good. We should take care to treat all un-annotated Thrift exceptions as client errors, since the majority fall into that category today.

This also leaves timeouts ill-specified, since it's unclear whether the client set an unreasonable deadline or the server is slow.

**Comment by kriskowal** [comment]
I concur. We should only annotate server errors. Thrift annotations also don’t require values, so we can do:

```thrift
service Fortunes {
  // Create a new Fortune synchronously.
  CreateResponse create();
  // Fetch an already-created Fortune by UUID.
  GetResponse get(1:GetRequest request) throws (
    1: ClientError clientError, 
    2: ServerError serverError (serverError),
  );
}
```

Some application errors probably correspond to gRPC error classes. I’m still wondering whether we only use gRPC error classes if the body is absent.

The complete list of gRPC error classes, and the corresponding TChannel error classes.

- Canceled: Cancelled (two L's :trollface:)
- Unknown: UnexpectedError
- Internal: UnexpectedError
- InvalidArgument: BadRequest
- DeadlineExceeded: Timeout
- NotFound
- AlreadyExists
- PermissionDenied
- Unauthenticated
- ResourceExhausted
- FailedPrecondition
- Aborted
- OutOfRange
- Unimplemented
- Unavailable: Busy or Declined
- DataLoss: FatalProtocolError

In the cases where there is no corresponding TChannel error frame, the behavior depends on whether there is a response payload. If there is a payload defined in IDL, the OK bit on the Call Response is 0. If there is no payload, these all funnel into UnexpectedError.

Here are the gRPC error classes and whether the client, server, or cosmic radiation (Thor) is responsible for the problem. I believe the distinction is germane to SRE, so please correct this if it doesn’t look right. I don’t think they’re germane to retry or routing policies.

- Canceled: not a problem
- Unknown: server
- Internal: server
- InvalidArgument: client
- DeadlineExceeded: client, server, network
- NotFound: client
- AlreadyExists: client
- PermissionDenied: client
- Unauthenticated: client
- ResourceExhausted: client
- FailedPrecondition: client
- Aborted: client
- OutOfRange: client
- Unimplemented: client
- Unavailable (TChannel Busy): client
- Unavailable (TChannel Declined): client, server
- DataLoss: network

**Comment by akshayjshah** [comment]
@kriskowal and @breerly (and anyone else who's interested): let's sync up on an implementation plan for this early next week, since it will significantly affect metrics collection.

**Comment by breerly** [comment]
Closing in favor of T859775
